/*
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import de.fhdw.iis1.tarot.ide.contentassist.antlr.internal.InternalTarotParser;
import de.fhdw.iis1.tarot.services.TarotGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class TarotParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TarotGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TarotGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
			builder.put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
			builder.put(grammarAccess.getAddSubExprAccess().getOpAlternatives_2_0_0(), "rule__AddSubExpr__OpAlternatives_2_0_0");
			builder.put(grammarAccess.getConditionalGotoAccess().getOpAlternatives_3_0(), "rule__ConditionalGoto__OpAlternatives_3_0");
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getLineAccess().getGroup(), "rule__Line__Group__0");
			builder.put(grammarAccess.getAssignmentAccess().getGroup(), "rule__Assignment__Group__0");
			builder.put(grammarAccess.getAddSubExprAccess().getGroup(), "rule__AddSubExpr__Group__0");
			builder.put(grammarAccess.getAddSubExprAccess().getGroup_2(), "rule__AddSubExpr__Group_2__0");
			builder.put(grammarAccess.getIntLiteralAccess().getGroup(), "rule__IntLiteral__Group__0");
			builder.put(grammarAccess.getInputAccess().getGroup(), "rule__Input__Group__0");
			builder.put(grammarAccess.getOutputAccess().getGroup(), "rule__Output__Group__0");
			builder.put(grammarAccess.getGotoAccess().getGroup(), "rule__Goto__Group__0");
			builder.put(grammarAccess.getConditionalGotoAccess().getGroup(), "rule__ConditionalGoto__Group__0");
			builder.put(grammarAccess.getStopAccess().getGroup(), "rule__Stop__Group__0");
			builder.put(grammarAccess.getProgramAccess().getLinesAssignment(), "rule__Program__LinesAssignment");
			builder.put(grammarAccess.getLineAccess().getNameAssignment_0(), "rule__Line__NameAssignment_0");
			builder.put(grammarAccess.getLineAccess().getInstructionAssignment_2(), "rule__Line__InstructionAssignment_2");
			builder.put(grammarAccess.getAssignmentAccess().getVarAssignment_0(), "rule__Assignment__VarAssignment_0");
			builder.put(grammarAccess.getAssignmentAccess().getExprAssignment_2(), "rule__Assignment__ExprAssignment_2");
			builder.put(grammarAccess.getAddSubExprAccess().getLeftAssignment_1(), "rule__AddSubExpr__LeftAssignment_1");
			builder.put(grammarAccess.getAddSubExprAccess().getOpAssignment_2_0(), "rule__AddSubExpr__OpAssignment_2_0");
			builder.put(grammarAccess.getAddSubExprAccess().getRightAssignment_2_1(), "rule__AddSubExpr__RightAssignment_2_1");
			builder.put(grammarAccess.getIntLiteralAccess().getValueAssignment_1(), "rule__IntLiteral__ValueAssignment_1");
			builder.put(grammarAccess.getInputAccess().getVarAssignment_1(), "rule__Input__VarAssignment_1");
			builder.put(grammarAccess.getOutputAccess().getVarAssignment_1(), "rule__Output__VarAssignment_1");
			builder.put(grammarAccess.getGotoAccess().getTargetAssignment_2(), "rule__Goto__TargetAssignment_2");
			builder.put(grammarAccess.getConditionalGotoAccess().getLeftAssignment_2(), "rule__ConditionalGoto__LeftAssignment_2");
			builder.put(grammarAccess.getConditionalGotoAccess().getOpAssignment_3(), "rule__ConditionalGoto__OpAssignment_3");
			builder.put(grammarAccess.getConditionalGotoAccess().getRightAssignment_4(), "rule__ConditionalGoto__RightAssignment_4");
			builder.put(grammarAccess.getConditionalGotoAccess().getTargetAssignment_9(), "rule__ConditionalGoto__TargetAssignment_9");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TarotGrammarAccess grammarAccess;

	@Override
	protected InternalTarotParser createParser() {
		InternalTarotParser result = new InternalTarotParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TarotGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TarotGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
