/**
 * generated by Xtext 2.41.0
 */
package de.fhdw.iis1.tarot.tarot.impl;

import de.fhdw.iis1.tarot.tarot.Ausdruck;
import de.fhdw.iis1.tarot.tarot.TarotPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ausdruck</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AusdruckImpl extends MinimalEObjectImpl.Container implements Ausdruck
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AusdruckImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TarotPackage.Literals.AUSDRUCK;
  }

} //AusdruckImpl
