/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot.impl;

import de.fhdw.iis1.tarot.tarot.Ganzzahl;
import de.fhdw.iis1.tarot.tarot.TarotPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ganzzahl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.impl.GanzzahlImpl#getWert <em>Wert</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GanzzahlImpl extends AusdruckImpl implements Ganzzahl
{
  /**
   * The default value of the '{@link #getWert() <em>Wert</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWert()
   * @generated
   * @ordered
   */
  protected static final int WERT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getWert() <em>Wert</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWert()
   * @generated
   * @ordered
   */
  protected int wert = WERT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GanzzahlImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TarotPackage.Literals.GANZZAHL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getWert()
  {
    return wert;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWert(int newWert)
  {
    int oldWert = wert;
    wert = newWert;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TarotPackage.GANZZAHL__WERT, oldWert, wert));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TarotPackage.GANZZAHL__WERT:
        return getWert();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TarotPackage.GANZZAHL__WERT:
        setWert((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TarotPackage.GANZZAHL__WERT:
        setWert(WERT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TarotPackage.GANZZAHL__WERT:
        return wert != WERT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (wert: ");
    result.append(wert);
    result.append(')');
    return result.toString();
  }

} //GanzzahlImpl
