/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot.impl;

import de.fhdw.iis1.tarot.tarot.GeheZu;
import de.fhdw.iis1.tarot.tarot.TarotPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Gehe Zu</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.impl.GeheZuImpl#getZiel <em>Ziel</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GeheZuImpl extends AnweisungImpl implements GeheZu
{
  /**
   * The default value of the '{@link #getZiel() <em>Ziel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZiel()
   * @generated
   * @ordered
   */
  protected static final String ZIEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getZiel() <em>Ziel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZiel()
   * @generated
   * @ordered
   */
  protected String ziel = ZIEL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GeheZuImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TarotPackage.Literals.GEHE_ZU;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getZiel()
  {
    return ziel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setZiel(String newZiel)
  {
    String oldZiel = ziel;
    ziel = newZiel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TarotPackage.GEHE_ZU__ZIEL, oldZiel, ziel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TarotPackage.GEHE_ZU__ZIEL:
        return getZiel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TarotPackage.GEHE_ZU__ZIEL:
        setZiel((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TarotPackage.GEHE_ZU__ZIEL:
        setZiel(ZIEL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TarotPackage.GEHE_ZU__ZIEL:
        return ZIEL_EDEFAULT == null ? ziel != null : !ZIEL_EDEFAULT.equals(ziel);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ziel: ");
    result.append(ziel);
    result.append(')');
    return result.toString();
  }

} //GeheZuImpl
