/**
 * generated by Xtext 2.41.0
 */
package de.fhdw.iis1.tarot.tarot.impl;

import de.fhdw.iis1.tarot.tarot.Halt;
import de.fhdw.iis1.tarot.tarot.TarotPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Halt</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class HaltImpl extends AnweisungImpl implements Halt
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HaltImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TarotPackage.Literals.HALT;
  }

} //HaltImpl
