/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot.impl;

import de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu;
import de.fhdw.iis1.tarot.tarot.TarotPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Konditionaler Gehe Zu</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.impl.KonditionalerGeheZuImpl#getLinks <em>Links</em>}</li>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.impl.KonditionalerGeheZuImpl#getOp <em>Op</em>}</li>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.impl.KonditionalerGeheZuImpl#getRechts <em>Rechts</em>}</li>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.impl.KonditionalerGeheZuImpl#getZiel <em>Ziel</em>}</li>
 * </ul>
 *
 * @generated
 */
public class KonditionalerGeheZuImpl extends AnweisungImpl implements KonditionalerGeheZu
{
  /**
   * The default value of the '{@link #getLinks() <em>Links</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinks()
   * @generated
   * @ordered
   */
  protected static final String LINKS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLinks() <em>Links</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinks()
   * @generated
   * @ordered
   */
  protected String links = LINKS_EDEFAULT;

  /**
   * The default value of the '{@link #getOp() <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOp()
   * @generated
   * @ordered
   */
  protected static final String OP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOp() <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOp()
   * @generated
   * @ordered
   */
  protected String op = OP_EDEFAULT;

  /**
   * The default value of the '{@link #getRechts() <em>Rechts</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRechts()
   * @generated
   * @ordered
   */
  protected static final String RECHTS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRechts() <em>Rechts</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRechts()
   * @generated
   * @ordered
   */
  protected String rechts = RECHTS_EDEFAULT;

  /**
   * The default value of the '{@link #getZiel() <em>Ziel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZiel()
   * @generated
   * @ordered
   */
  protected static final String ZIEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getZiel() <em>Ziel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZiel()
   * @generated
   * @ordered
   */
  protected String ziel = ZIEL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected KonditionalerGeheZuImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TarotPackage.Literals.KONDITIONALER_GEHE_ZU;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLinks()
  {
    return links;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLinks(String newLinks)
  {
    String oldLinks = links;
    links = newLinks;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TarotPackage.KONDITIONALER_GEHE_ZU__LINKS, oldLinks, links));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOp()
  {
    return op;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOp(String newOp)
  {
    String oldOp = op;
    op = newOp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TarotPackage.KONDITIONALER_GEHE_ZU__OP, oldOp, op));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRechts()
  {
    return rechts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRechts(String newRechts)
  {
    String oldRechts = rechts;
    rechts = newRechts;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TarotPackage.KONDITIONALER_GEHE_ZU__RECHTS, oldRechts, rechts));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getZiel()
  {
    return ziel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setZiel(String newZiel)
  {
    String oldZiel = ziel;
    ziel = newZiel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TarotPackage.KONDITIONALER_GEHE_ZU__ZIEL, oldZiel, ziel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TarotPackage.KONDITIONALER_GEHE_ZU__LINKS:
        return getLinks();
      case TarotPackage.KONDITIONALER_GEHE_ZU__OP:
        return getOp();
      case TarotPackage.KONDITIONALER_GEHE_ZU__RECHTS:
        return getRechts();
      case TarotPackage.KONDITIONALER_GEHE_ZU__ZIEL:
        return getZiel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TarotPackage.KONDITIONALER_GEHE_ZU__LINKS:
        setLinks((String)newValue);
        return;
      case TarotPackage.KONDITIONALER_GEHE_ZU__OP:
        setOp((String)newValue);
        return;
      case TarotPackage.KONDITIONALER_GEHE_ZU__RECHTS:
        setRechts((String)newValue);
        return;
      case TarotPackage.KONDITIONALER_GEHE_ZU__ZIEL:
        setZiel((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TarotPackage.KONDITIONALER_GEHE_ZU__LINKS:
        setLinks(LINKS_EDEFAULT);
        return;
      case TarotPackage.KONDITIONALER_GEHE_ZU__OP:
        setOp(OP_EDEFAULT);
        return;
      case TarotPackage.KONDITIONALER_GEHE_ZU__RECHTS:
        setRechts(RECHTS_EDEFAULT);
        return;
      case TarotPackage.KONDITIONALER_GEHE_ZU__ZIEL:
        setZiel(ZIEL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TarotPackage.KONDITIONALER_GEHE_ZU__LINKS:
        return LINKS_EDEFAULT == null ? links != null : !LINKS_EDEFAULT.equals(links);
      case TarotPackage.KONDITIONALER_GEHE_ZU__OP:
        return OP_EDEFAULT == null ? op != null : !OP_EDEFAULT.equals(op);
      case TarotPackage.KONDITIONALER_GEHE_ZU__RECHTS:
        return RECHTS_EDEFAULT == null ? rechts != null : !RECHTS_EDEFAULT.equals(rechts);
      case TarotPackage.KONDITIONALER_GEHE_ZU__ZIEL:
        return ZIEL_EDEFAULT == null ? ziel != null : !ZIEL_EDEFAULT.equals(ziel);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (links: ");
    result.append(links);
    result.append(", op: ");
    result.append(op);
    result.append(", rechts: ");
    result.append(rechts);
    result.append(", ziel: ");
    result.append(ziel);
    result.append(')');
    return result.toString();
  }

} //KonditionalerGeheZuImpl
