/**
 * generated by Xtext 2.41.0
 */
package de.fhdw.iis1.tarot.tarot.impl;

import de.fhdw.iis1.tarot.tarot.Anweisung;
import de.fhdw.iis1.tarot.tarot.Ausdruck;
import de.fhdw.iis1.tarot.tarot.Ausgabe;
import de.fhdw.iis1.tarot.tarot.Eingabe;
import de.fhdw.iis1.tarot.tarot.Ganzzahl;
import de.fhdw.iis1.tarot.tarot.GeheZu;
import de.fhdw.iis1.tarot.tarot.Halt;
import de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu;
import de.fhdw.iis1.tarot.tarot.Programm;
import de.fhdw.iis1.tarot.tarot.StrichOperation;
import de.fhdw.iis1.tarot.tarot.TarotFactory;
import de.fhdw.iis1.tarot.tarot.TarotPackage;
import de.fhdw.iis1.tarot.tarot.Zeile;
import de.fhdw.iis1.tarot.tarot.Zuordnung;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class TarotPackageImpl extends EPackageImpl implements TarotPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass programmEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass zeileEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass anweisungEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass zuordnungEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ausdruckEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass strichOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ganzzahlEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass eingabeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ausgabeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass geheZuEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass konditionalerGeheZuEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass haltEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private TarotPackageImpl()
  {
    super(eNS_URI, TarotFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link TarotPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static TarotPackage init()
  {
    if (isInited) return (TarotPackage)EPackage.Registry.INSTANCE.getEPackage(TarotPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredTarotPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    TarotPackageImpl theTarotPackage = registeredTarotPackage instanceof TarotPackageImpl ? (TarotPackageImpl)registeredTarotPackage : new TarotPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theTarotPackage.createPackageContents();

    // Initialize created meta-data
    theTarotPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theTarotPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(TarotPackage.eNS_URI, theTarotPackage);
    return theTarotPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getProgramm()
  {
    return programmEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getProgramm_Zeilen()
  {
    return (EReference)programmEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getZeile()
  {
    return zeileEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getZeile_Name()
  {
    return (EAttribute)zeileEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getZeile_Anweisung()
  {
    return (EReference)zeileEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAnweisung()
  {
    return anweisungEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getZuordnung()
  {
    return zuordnungEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getZuordnung_Var()
  {
    return (EAttribute)zuordnungEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getZuordnung_Ausdruck()
  {
    return (EReference)zuordnungEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAusdruck()
  {
    return ausdruckEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStrichOperation()
  {
    return strichOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStrichOperation_Links()
  {
    return (EAttribute)strichOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStrichOperation_Op()
  {
    return (EAttribute)strichOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStrichOperation_Rechts()
  {
    return (EAttribute)strichOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGanzzahl()
  {
    return ganzzahlEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGanzzahl_Wert()
  {
    return (EAttribute)ganzzahlEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEingabe()
  {
    return eingabeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEingabe_Var()
  {
    return (EAttribute)eingabeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAusgabe()
  {
    return ausgabeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAusgabe_Var()
  {
    return (EAttribute)ausgabeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGeheZu()
  {
    return geheZuEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGeheZu_Ziel()
  {
    return (EAttribute)geheZuEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getKonditionalerGeheZu()
  {
    return konditionalerGeheZuEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getKonditionalerGeheZu_Links()
  {
    return (EAttribute)konditionalerGeheZuEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getKonditionalerGeheZu_Op()
  {
    return (EAttribute)konditionalerGeheZuEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getKonditionalerGeheZu_Rechts()
  {
    return (EAttribute)konditionalerGeheZuEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getKonditionalerGeheZu_Ziel()
  {
    return (EAttribute)konditionalerGeheZuEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getHalt()
  {
    return haltEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TarotFactory getTarotFactory()
  {
    return (TarotFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    programmEClass = createEClass(PROGRAMM);
    createEReference(programmEClass, PROGRAMM__ZEILEN);

    zeileEClass = createEClass(ZEILE);
    createEAttribute(zeileEClass, ZEILE__NAME);
    createEReference(zeileEClass, ZEILE__ANWEISUNG);

    anweisungEClass = createEClass(ANWEISUNG);

    zuordnungEClass = createEClass(ZUORDNUNG);
    createEAttribute(zuordnungEClass, ZUORDNUNG__VAR);
    createEReference(zuordnungEClass, ZUORDNUNG__AUSDRUCK);

    ausdruckEClass = createEClass(AUSDRUCK);

    strichOperationEClass = createEClass(STRICH_OPERATION);
    createEAttribute(strichOperationEClass, STRICH_OPERATION__LINKS);
    createEAttribute(strichOperationEClass, STRICH_OPERATION__OP);
    createEAttribute(strichOperationEClass, STRICH_OPERATION__RECHTS);

    ganzzahlEClass = createEClass(GANZZAHL);
    createEAttribute(ganzzahlEClass, GANZZAHL__WERT);

    eingabeEClass = createEClass(EINGABE);
    createEAttribute(eingabeEClass, EINGABE__VAR);

    ausgabeEClass = createEClass(AUSGABE);
    createEAttribute(ausgabeEClass, AUSGABE__VAR);

    geheZuEClass = createEClass(GEHE_ZU);
    createEAttribute(geheZuEClass, GEHE_ZU__ZIEL);

    konditionalerGeheZuEClass = createEClass(KONDITIONALER_GEHE_ZU);
    createEAttribute(konditionalerGeheZuEClass, KONDITIONALER_GEHE_ZU__LINKS);
    createEAttribute(konditionalerGeheZuEClass, KONDITIONALER_GEHE_ZU__OP);
    createEAttribute(konditionalerGeheZuEClass, KONDITIONALER_GEHE_ZU__RECHTS);
    createEAttribute(konditionalerGeheZuEClass, KONDITIONALER_GEHE_ZU__ZIEL);

    haltEClass = createEClass(HALT);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    zuordnungEClass.getESuperTypes().add(this.getAnweisung());
    strichOperationEClass.getESuperTypes().add(this.getAusdruck());
    ganzzahlEClass.getESuperTypes().add(this.getAusdruck());
    eingabeEClass.getESuperTypes().add(this.getAnweisung());
    ausgabeEClass.getESuperTypes().add(this.getAnweisung());
    geheZuEClass.getESuperTypes().add(this.getAnweisung());
    konditionalerGeheZuEClass.getESuperTypes().add(this.getAnweisung());
    haltEClass.getESuperTypes().add(this.getAnweisung());

    // Initialize classes and features; add operations and parameters
    initEClass(programmEClass, Programm.class, "Programm", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getProgramm_Zeilen(), this.getZeile(), null, "zeilen", null, 0, -1, Programm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(zeileEClass, Zeile.class, "Zeile", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getZeile_Name(), ecorePackage.getEString(), "name", null, 0, 1, Zeile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getZeile_Anweisung(), this.getAnweisung(), null, "anweisung", null, 0, 1, Zeile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(anweisungEClass, Anweisung.class, "Anweisung", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(zuordnungEClass, Zuordnung.class, "Zuordnung", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getZuordnung_Var(), ecorePackage.getEString(), "var", null, 0, 1, Zuordnung.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getZuordnung_Ausdruck(), this.getAusdruck(), null, "ausdruck", null, 0, 1, Zuordnung.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ausdruckEClass, Ausdruck.class, "Ausdruck", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(strichOperationEClass, StrichOperation.class, "StrichOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStrichOperation_Links(), ecorePackage.getEString(), "links", null, 0, 1, StrichOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStrichOperation_Op(), ecorePackage.getEString(), "op", null, 0, 1, StrichOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStrichOperation_Rechts(), ecorePackage.getEString(), "rechts", null, 0, 1, StrichOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ganzzahlEClass, Ganzzahl.class, "Ganzzahl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGanzzahl_Wert(), ecorePackage.getEInt(), "wert", null, 0, 1, Ganzzahl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(eingabeEClass, Eingabe.class, "Eingabe", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEingabe_Var(), ecorePackage.getEString(), "var", null, 0, 1, Eingabe.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ausgabeEClass, Ausgabe.class, "Ausgabe", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAusgabe_Var(), ecorePackage.getEString(), "var", null, 0, 1, Ausgabe.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(geheZuEClass, GeheZu.class, "GeheZu", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGeheZu_Ziel(), ecorePackage.getEString(), "ziel", null, 0, 1, GeheZu.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(konditionalerGeheZuEClass, KonditionalerGeheZu.class, "KonditionalerGeheZu", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getKonditionalerGeheZu_Links(), ecorePackage.getEString(), "links", null, 0, 1, KonditionalerGeheZu.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getKonditionalerGeheZu_Op(), ecorePackage.getEString(), "op", null, 0, 1, KonditionalerGeheZu.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getKonditionalerGeheZu_Rechts(), ecorePackage.getEString(), "rechts", null, 0, 1, KonditionalerGeheZu.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getKonditionalerGeheZu_Ziel(), ecorePackage.getEString(), "ziel", null, 0, 1, KonditionalerGeheZu.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(haltEClass, Halt.class, "Halt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    // Create resource
    createResource(eNS_URI);
  }

} //TarotPackageImpl
