/**
 * generated by Xtext 2.41.0
 */
package de.fhdw.iis1.tarot.tarot.impl;

import de.fhdw.iis1.tarot.tarot.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class TarotFactoryImpl extends EFactoryImpl implements TarotFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static TarotFactory init()
  {
    try
    {
      TarotFactory theTarotFactory = (TarotFactory)EPackage.Registry.INSTANCE.getEFactory(TarotPackage.eNS_URI);
      if (theTarotFactory != null)
      {
        return theTarotFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new TarotFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TarotFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case TarotPackage.PROGRAMM: return createProgramm();
      case TarotPackage.ZEILE: return createZeile();
      case TarotPackage.ANWEISUNG: return createAnweisung();
      case TarotPackage.ZUORDNUNG: return createZuordnung();
      case TarotPackage.AUSDRUCK: return createAusdruck();
      case TarotPackage.STRICH_OPERATION: return createStrichOperation();
      case TarotPackage.GANZZAHL: return createGanzzahl();
      case TarotPackage.EINGABE: return createEingabe();
      case TarotPackage.AUSGABE: return createAusgabe();
      case TarotPackage.GEHE_ZU: return createGeheZu();
      case TarotPackage.KONDITIONALER_GEHE_ZU: return createKonditionalerGeheZu();
      case TarotPackage.HALT: return createHalt();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Programm createProgramm()
  {
    ProgrammImpl programm = new ProgrammImpl();
    return programm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Zeile createZeile()
  {
    ZeileImpl zeile = new ZeileImpl();
    return zeile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Anweisung createAnweisung()
  {
    AnweisungImpl anweisung = new AnweisungImpl();
    return anweisung;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Zuordnung createZuordnung()
  {
    ZuordnungImpl zuordnung = new ZuordnungImpl();
    return zuordnung;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ausdruck createAusdruck()
  {
    AusdruckImpl ausdruck = new AusdruckImpl();
    return ausdruck;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StrichOperation createStrichOperation()
  {
    StrichOperationImpl strichOperation = new StrichOperationImpl();
    return strichOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ganzzahl createGanzzahl()
  {
    GanzzahlImpl ganzzahl = new GanzzahlImpl();
    return ganzzahl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Eingabe createEingabe()
  {
    EingabeImpl eingabe = new EingabeImpl();
    return eingabe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ausgabe createAusgabe()
  {
    AusgabeImpl ausgabe = new AusgabeImpl();
    return ausgabe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GeheZu createGeheZu()
  {
    GeheZuImpl geheZu = new GeheZuImpl();
    return geheZu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public KonditionalerGeheZu createKonditionalerGeheZu()
  {
    KonditionalerGeheZuImpl konditionalerGeheZu = new KonditionalerGeheZuImpl();
    return konditionalerGeheZu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Halt createHalt()
  {
    HaltImpl halt = new HaltImpl();
    return halt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TarotPackage getTarotPackage()
  {
    return (TarotPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static TarotPackage getPackage()
  {
    return TarotPackage.eINSTANCE;
  }

} //TarotFactoryImpl
