/**
 * generated by Xtext 2.41.0
 */
package de.fhdw.iis1.tarot.tarot.impl;

import de.fhdw.iis1.tarot.tarot.Ausdruck;
import de.fhdw.iis1.tarot.tarot.TarotPackage;
import de.fhdw.iis1.tarot.tarot.Zuordnung;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Zuordnung</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.impl.ZuordnungImpl#getVar <em>Var</em>}</li>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.impl.ZuordnungImpl#getAusdruck <em>Ausdruck</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ZuordnungImpl extends AnweisungImpl implements Zuordnung
{
  /**
   * The default value of the '{@link #getVar() <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected static final String VAR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVar() <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected String var = VAR_EDEFAULT;

  /**
   * The cached value of the '{@link #getAusdruck() <em>Ausdruck</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAusdruck()
   * @generated
   * @ordered
   */
  protected Ausdruck ausdruck;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ZuordnungImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TarotPackage.Literals.ZUORDNUNG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVar()
  {
    return var;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVar(String newVar)
  {
    String oldVar = var;
    var = newVar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TarotPackage.ZUORDNUNG__VAR, oldVar, var));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ausdruck getAusdruck()
  {
    return ausdruck;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAusdruck(Ausdruck newAusdruck, NotificationChain msgs)
  {
    Ausdruck oldAusdruck = ausdruck;
    ausdruck = newAusdruck;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TarotPackage.ZUORDNUNG__AUSDRUCK, oldAusdruck, newAusdruck);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAusdruck(Ausdruck newAusdruck)
  {
    if (newAusdruck != ausdruck)
    {
      NotificationChain msgs = null;
      if (ausdruck != null)
        msgs = ((InternalEObject)ausdruck).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TarotPackage.ZUORDNUNG__AUSDRUCK, null, msgs);
      if (newAusdruck != null)
        msgs = ((InternalEObject)newAusdruck).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TarotPackage.ZUORDNUNG__AUSDRUCK, null, msgs);
      msgs = basicSetAusdruck(newAusdruck, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TarotPackage.ZUORDNUNG__AUSDRUCK, newAusdruck, newAusdruck));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TarotPackage.ZUORDNUNG__AUSDRUCK:
        return basicSetAusdruck(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TarotPackage.ZUORDNUNG__VAR:
        return getVar();
      case TarotPackage.ZUORDNUNG__AUSDRUCK:
        return getAusdruck();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TarotPackage.ZUORDNUNG__VAR:
        setVar((String)newValue);
        return;
      case TarotPackage.ZUORDNUNG__AUSDRUCK:
        setAusdruck((Ausdruck)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TarotPackage.ZUORDNUNG__VAR:
        setVar(VAR_EDEFAULT);
        return;
      case TarotPackage.ZUORDNUNG__AUSDRUCK:
        setAusdruck((Ausdruck)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TarotPackage.ZUORDNUNG__VAR:
        return VAR_EDEFAULT == null ? var != null : !VAR_EDEFAULT.equals(var);
      case TarotPackage.ZUORDNUNG__AUSDRUCK:
        return ausdruck != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (var: ");
    result.append(var);
    result.append(')');
    return result.toString();
  }

} //ZuordnungImpl
