/*
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTarotScopeProvider extends DelegatingScopeProvider {
}
