/**
 * generated by Xtext 2.41.0
 */
package de.fhdw.iis1.tarot.tarot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ausdruck</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getAusdruck()
 * @model
 * @generated
 */
public interface Ausdruck extends EObject
{
} // Ausdruck
