/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditional Goto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto#getLeft <em>Left</em>}</li>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto#getOp <em>Op</em>}</li>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto#getRight <em>Right</em>}</li>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getConditionalGoto()
 * @model
 * @generated
 */
public interface ConditionalGoto extends Instruction
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' attribute.
   * @see #setLeft(String)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getConditionalGoto_Left()
   * @model
   * @generated
   */
  String getLeft();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto#getLeft <em>Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' attribute.
   * @see #getLeft()
   * @generated
   */
  void setLeft(String value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getConditionalGoto_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' attribute.
   * @see #setRight(String)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getConditionalGoto_Right()
   * @model
   * @generated
   */
  String getRight();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto#getRight <em>Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' attribute.
   * @see #getRight()
   * @generated
   */
  void setRight(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(Line)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getConditionalGoto_Target()
   * @model
   * @generated
   */
  Line getTarget();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Line value);

} // ConditionalGoto
