/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
