/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ganzzahl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.Ganzzahl#getWert <em>Wert</em>}</li>
 * </ul>
 *
 * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getGanzzahl()
 * @model
 * @generated
 */
public interface Ganzzahl extends Ausdruck
{
  /**
   * Returns the value of the '<em><b>Wert</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wert</em>' attribute.
   * @see #setWert(int)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getGanzzahl_Wert()
   * @model
   * @generated
   */
  int getWert();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.Ganzzahl#getWert <em>Wert</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wert</em>' attribute.
   * @see #getWert()
   * @generated
   */
  void setWert(int value);

} // Ganzzahl
