/**
 * generated by Xtext 2.41.0
 */
package de.fhdw.iis1.tarot.tarot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Halt</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getHalt()
 * @model
 * @generated
 */
public interface Halt extends Anweisung
{
} // Halt
