/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Line</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.Line#getName <em>Name</em>}</li>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.Line#getInstruction <em>Instruction</em>}</li>
 * </ul>
 *
 * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getLine()
 * @model
 * @generated
 */
public interface Line extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getLine_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.Line#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instruction</em>' containment reference.
   * @see #setInstruction(Instruction)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getLine_Instruction()
   * @model containment="true"
   * @generated
   */
  Instruction getInstruction();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.Line#getInstruction <em>Instruction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Instruction</em>' containment reference.
   * @see #getInstruction()
   * @generated
   */
  void setInstruction(Instruction value);

} // Line
