/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stop</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getStop()
 * @model
 * @generated
 */
public interface Stop extends Instruction
{
} // Stop
