/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Strich Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.StrichOperation#getLinks <em>Links</em>}</li>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.StrichOperation#getOp <em>Op</em>}</li>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.StrichOperation#getRechts <em>Rechts</em>}</li>
 * </ul>
 *
 * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getStrichOperation()
 * @model
 * @generated
 */
public interface StrichOperation extends Ausdruck
{
  /**
   * Returns the value of the '<em><b>Links</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Links</em>' attribute.
   * @see #setLinks(String)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getStrichOperation_Links()
   * @model
   * @generated
   */
  String getLinks();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.StrichOperation#getLinks <em>Links</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Links</em>' attribute.
   * @see #getLinks()
   * @generated
   */
  void setLinks(String value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getStrichOperation_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.StrichOperation#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Rechts</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rechts</em>' attribute.
   * @see #setRechts(String)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getStrichOperation_Rechts()
   * @model
   * @generated
   */
  String getRechts();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.StrichOperation#getRechts <em>Rechts</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rechts</em>' attribute.
   * @see #getRechts()
   * @generated
   */
  void setRechts(String value);

} // StrichOperation
