/**
 * generated by Xtext 2.41.0
 */
package de.fhdw.iis1.tarot.tarot;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.fhdw.iis1.tarot.tarot.TarotPackage
 * @generated
 */
public interface TarotFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TarotFactory eINSTANCE = de.fhdw.iis1.tarot.tarot.impl.TarotFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Programm</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Programm</em>'.
   * @generated
   */
  Programm createProgramm();

  /**
   * Returns a new object of class '<em>Zeile</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Zeile</em>'.
   * @generated
   */
  Zeile createZeile();

  /**
   * Returns a new object of class '<em>Anweisung</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Anweisung</em>'.
   * @generated
   */
  Anweisung createAnweisung();

  /**
   * Returns a new object of class '<em>Zuordnung</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Zuordnung</em>'.
   * @generated
   */
  Zuordnung createZuordnung();

  /**
   * Returns a new object of class '<em>Ausdruck</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ausdruck</em>'.
   * @generated
   */
  Ausdruck createAusdruck();

  /**
   * Returns a new object of class '<em>Strich Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Strich Operation</em>'.
   * @generated
   */
  StrichOperation createStrichOperation();

  /**
   * Returns a new object of class '<em>Ganzzahl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ganzzahl</em>'.
   * @generated
   */
  Ganzzahl createGanzzahl();

  /**
   * Returns a new object of class '<em>Eingabe</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Eingabe</em>'.
   * @generated
   */
  Eingabe createEingabe();

  /**
   * Returns a new object of class '<em>Ausgabe</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ausgabe</em>'.
   * @generated
   */
  Ausgabe createAusgabe();

  /**
   * Returns a new object of class '<em>Gehe Zu</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Gehe Zu</em>'.
   * @generated
   */
  GeheZu createGeheZu();

  /**
   * Returns a new object of class '<em>Konditionaler Gehe Zu</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Konditionaler Gehe Zu</em>'.
   * @generated
   */
  KonditionalerGeheZu createKonditionalerGeheZu();

  /**
   * Returns a new object of class '<em>Halt</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Halt</em>'.
   * @generated
   */
  Halt createHalt();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TarotPackage getTarotPackage();

} //TarotFactory
