/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.fhdw.iis1.tarot.tarot.TarotFactory
 * @model kind="package"
 * @generated
 */
public interface TarotPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tarot";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.fhdw.de/iis1/tarot/Tarot";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tarot";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TarotPackage eINSTANCE = de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl.init();

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.ProgramImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Lines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__LINES = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.LineImpl <em>Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.LineImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getLine()
   * @generated
   */
  int LINE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE__NAME = 0;

  /**
   * The feature id for the '<em><b>Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE__INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.InstructionImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 2;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.AssignmentImpl <em>Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.AssignmentImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getAssignment()
   * @generated
   */
  int ASSIGNMENT = 3;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__VAR = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__EXPR = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.ExpressionImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 4;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.AddSubExprImpl <em>Add Sub Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.AddSubExprImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getAddSubExpr()
   * @generated
   */
  int ADD_SUB_EXPR = 5;

  /**
   * The feature id for the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_SUB_EXPR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_SUB_EXPR__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_SUB_EXPR__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Add Sub Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_SUB_EXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.IntLiteralImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.InputImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getInput()
   * @generated
   */
  int INPUT = 7;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__VAR = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.OutputImpl <em>Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.OutputImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getOutput()
   * @generated
   */
  int OUTPUT = 8;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__VAR = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.GotoImpl <em>Goto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.GotoImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getGoto()
   * @generated
   */
  int GOTO = 9;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO__TARGET = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Goto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.ConditionalGotoImpl <em>Conditional Goto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.ConditionalGotoImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getConditionalGoto()
   * @generated
   */
  int CONDITIONAL_GOTO = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_GOTO__LEFT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_GOTO__OP = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_GOTO__RIGHT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_GOTO__TARGET = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Conditional Goto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_GOTO_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.StopImpl <em>Stop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.StopImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getStop()
   * @generated
   */
  int STOP = 11;

  /**
   * The number of structural features of the '<em>Stop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link de.fhdw.iis1.tarot.tarot.Program#getLines <em>Lines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lines</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Program#getLines()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Lines();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Line <em>Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Line</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Line
   * @generated
   */
  EClass getLine();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.Line#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Line#getName()
   * @see #getLine()
   * @generated
   */
  EAttribute getLine_Name();

  /**
   * Returns the meta object for the containment reference '{@link de.fhdw.iis1.tarot.tarot.Line#getInstruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instruction</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Line#getInstruction()
   * @see #getLine()
   * @generated
   */
  EReference getLine_Instruction();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Assignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Assignment
   * @generated
   */
  EClass getAssignment();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.Assignment#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Assignment#getVar()
   * @see #getAssignment()
   * @generated
   */
  EAttribute getAssignment_Var();

  /**
   * Returns the meta object for the containment reference '{@link de.fhdw.iis1.tarot.tarot.Assignment#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Assignment#getExpr()
   * @see #getAssignment()
   * @generated
   */
  EReference getAssignment_Expr();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.AddSubExpr <em>Add Sub Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Sub Expr</em>'.
   * @see de.fhdw.iis1.tarot.tarot.AddSubExpr
   * @generated
   */
  EClass getAddSubExpr();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.AddSubExpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left</em>'.
   * @see de.fhdw.iis1.tarot.tarot.AddSubExpr#getLeft()
   * @see #getAddSubExpr()
   * @generated
   */
  EAttribute getAddSubExpr_Left();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.AddSubExpr#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see de.fhdw.iis1.tarot.tarot.AddSubExpr#getOp()
   * @see #getAddSubExpr()
   * @generated
   */
  EAttribute getAddSubExpr_Op();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.AddSubExpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right</em>'.
   * @see de.fhdw.iis1.tarot.tarot.AddSubExpr#getRight()
   * @see #getAddSubExpr()
   * @generated
   */
  EAttribute getAddSubExpr_Right();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see de.fhdw.iis1.tarot.tarot.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.IntLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.fhdw.iis1.tarot.tarot.IntLiteral#getValue()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Value();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.Input#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Input#getVar()
   * @see #getInput()
   * @generated
   */
  EAttribute getInput_Var();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Output <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Output
   * @generated
   */
  EClass getOutput();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.Output#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Output#getVar()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_Var();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Goto <em>Goto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goto</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Goto
   * @generated
   */
  EClass getGoto();

  /**
   * Returns the meta object for the reference '{@link de.fhdw.iis1.tarot.tarot.Goto#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Goto#getTarget()
   * @see #getGoto()
   * @generated
   */
  EReference getGoto_Target();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto <em>Conditional Goto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditional Goto</em>'.
   * @see de.fhdw.iis1.tarot.tarot.ConditionalGoto
   * @generated
   */
  EClass getConditionalGoto();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left</em>'.
   * @see de.fhdw.iis1.tarot.tarot.ConditionalGoto#getLeft()
   * @see #getConditionalGoto()
   * @generated
   */
  EAttribute getConditionalGoto_Left();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see de.fhdw.iis1.tarot.tarot.ConditionalGoto#getOp()
   * @see #getConditionalGoto()
   * @generated
   */
  EAttribute getConditionalGoto_Op();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right</em>'.
   * @see de.fhdw.iis1.tarot.tarot.ConditionalGoto#getRight()
   * @see #getConditionalGoto()
   * @generated
   */
  EAttribute getConditionalGoto_Right();

  /**
   * Returns the meta object for the reference '{@link de.fhdw.iis1.tarot.tarot.ConditionalGoto#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see de.fhdw.iis1.tarot.tarot.ConditionalGoto#getTarget()
   * @see #getConditionalGoto()
   * @generated
   */
  EReference getConditionalGoto_Target();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Stop <em>Stop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stop</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Stop
   * @generated
   */
  EClass getStop();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TarotFactory getTarotFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.ProgramImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Lines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__LINES = eINSTANCE.getProgram_Lines();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.LineImpl <em>Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.LineImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getLine()
     * @generated
     */
    EClass LINE = eINSTANCE.getLine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINE__NAME = eINSTANCE.getLine_Name();

    /**
     * The meta object literal for the '<em><b>Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINE__INSTRUCTION = eINSTANCE.getLine_Instruction();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.InstructionImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.AssignmentImpl <em>Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.AssignmentImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getAssignment()
     * @generated
     */
    EClass ASSIGNMENT = eINSTANCE.getAssignment();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGNMENT__VAR = eINSTANCE.getAssignment_Var();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT__EXPR = eINSTANCE.getAssignment_Expr();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.ExpressionImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.AddSubExprImpl <em>Add Sub Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.AddSubExprImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getAddSubExpr()
     * @generated
     */
    EClass ADD_SUB_EXPR = eINSTANCE.getAddSubExpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD_SUB_EXPR__LEFT = eINSTANCE.getAddSubExpr_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD_SUB_EXPR__OP = eINSTANCE.getAddSubExpr_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD_SUB_EXPR__RIGHT = eINSTANCE.getAddSubExpr_Right();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.IntLiteralImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VALUE = eINSTANCE.getIntLiteral_Value();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.InputImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT__VAR = eINSTANCE.getInput_Var();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.OutputImpl <em>Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.OutputImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getOutput()
     * @generated
     */
    EClass OUTPUT = eINSTANCE.getOutput();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__VAR = eINSTANCE.getOutput_Var();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.GotoImpl <em>Goto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.GotoImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getGoto()
     * @generated
     */
    EClass GOTO = eINSTANCE.getGoto();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GOTO__TARGET = eINSTANCE.getGoto_Target();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.ConditionalGotoImpl <em>Conditional Goto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.ConditionalGotoImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getConditionalGoto()
     * @generated
     */
    EClass CONDITIONAL_GOTO = eINSTANCE.getConditionalGoto();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONAL_GOTO__LEFT = eINSTANCE.getConditionalGoto_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONAL_GOTO__OP = eINSTANCE.getConditionalGoto_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONAL_GOTO__RIGHT = eINSTANCE.getConditionalGoto_Right();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL_GOTO__TARGET = eINSTANCE.getConditionalGoto_Target();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.StopImpl <em>Stop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.StopImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getStop()
     * @generated
     */
    EClass STOP = eINSTANCE.getStop();

  }

} //TarotPackage
