/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.fhdw.iis1.tarot.tarot.TarotFactory
 * @model kind="package"
 * @generated
 */
public interface TarotPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tarot";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.fhdw.de/iis1/tarot/Tarot";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tarot";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TarotPackage eINSTANCE = de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl.init();

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.ProgrammImpl <em>Programm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.ProgrammImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getProgramm()
   * @generated
   */
  int PROGRAMM = 0;

  /**
   * The feature id for the '<em><b>Zeilen</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMM__ZEILEN = 0;

  /**
   * The number of structural features of the '<em>Programm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.ZeileImpl <em>Zeile</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.ZeileImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getZeile()
   * @generated
   */
  int ZEILE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZEILE__NAME = 0;

  /**
   * The feature id for the '<em><b>Anweisung</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZEILE__ANWEISUNG = 1;

  /**
   * The number of structural features of the '<em>Zeile</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZEILE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.AnweisungImpl <em>Anweisung</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.AnweisungImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getAnweisung()
   * @generated
   */
  int ANWEISUNG = 2;

  /**
   * The number of structural features of the '<em>Anweisung</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANWEISUNG_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.ZuordnungImpl <em>Zuordnung</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.ZuordnungImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getZuordnung()
   * @generated
   */
  int ZUORDNUNG = 3;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZUORDNUNG__VAR = ANWEISUNG_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ausdruck</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZUORDNUNG__AUSDRUCK = ANWEISUNG_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Zuordnung</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZUORDNUNG_FEATURE_COUNT = ANWEISUNG_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.AusdruckImpl <em>Ausdruck</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.AusdruckImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getAusdruck()
   * @generated
   */
  int AUSDRUCK = 4;

  /**
   * The number of structural features of the '<em>Ausdruck</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUSDRUCK_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.StrichOperationImpl <em>Strich Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.StrichOperationImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getStrichOperation()
   * @generated
   */
  int STRICH_OPERATION = 5;

  /**
   * The feature id for the '<em><b>Links</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRICH_OPERATION__LINKS = AUSDRUCK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRICH_OPERATION__OP = AUSDRUCK_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Rechts</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRICH_OPERATION__RECHTS = AUSDRUCK_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Strich Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRICH_OPERATION_FEATURE_COUNT = AUSDRUCK_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.GanzzahlImpl <em>Ganzzahl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.GanzzahlImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getGanzzahl()
   * @generated
   */
  int GANZZAHL = 6;

  /**
   * The feature id for the '<em><b>Wert</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GANZZAHL__WERT = AUSDRUCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ganzzahl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GANZZAHL_FEATURE_COUNT = AUSDRUCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.EingabeImpl <em>Eingabe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.EingabeImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getEingabe()
   * @generated
   */
  int EINGABE = 7;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINGABE__VAR = ANWEISUNG_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Eingabe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINGABE_FEATURE_COUNT = ANWEISUNG_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.AusgabeImpl <em>Ausgabe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.AusgabeImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getAusgabe()
   * @generated
   */
  int AUSGABE = 8;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUSGABE__VAR = ANWEISUNG_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ausgabe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUSGABE_FEATURE_COUNT = ANWEISUNG_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.GeheZuImpl <em>Gehe Zu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.GeheZuImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getGeheZu()
   * @generated
   */
  int GEHE_ZU = 9;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEHE_ZU__TARGET = ANWEISUNG_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Gehe Zu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEHE_ZU_FEATURE_COUNT = ANWEISUNG_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.KonditionalerGeheZuImpl <em>Konditionaler Gehe Zu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.KonditionalerGeheZuImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getKonditionalerGeheZu()
   * @generated
   */
  int KONDITIONALER_GEHE_ZU = 10;

  /**
   * The feature id for the '<em><b>Links</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KONDITIONALER_GEHE_ZU__LINKS = ANWEISUNG_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KONDITIONALER_GEHE_ZU__OP = ANWEISUNG_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Rechts</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KONDITIONALER_GEHE_ZU__RECHTS = ANWEISUNG_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Ziel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KONDITIONALER_GEHE_ZU__ZIEL = ANWEISUNG_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Konditionaler Gehe Zu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KONDITIONALER_GEHE_ZU_FEATURE_COUNT = ANWEISUNG_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link de.fhdw.iis1.tarot.tarot.impl.HaltImpl <em>Halt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.iis1.tarot.tarot.impl.HaltImpl
   * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getHalt()
   * @generated
   */
  int HALT = 11;

  /**
   * The number of structural features of the '<em>Halt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HALT_FEATURE_COUNT = ANWEISUNG_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Programm <em>Programm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Programm</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Programm
   * @generated
   */
  EClass getProgramm();

  /**
   * Returns the meta object for the containment reference list '{@link de.fhdw.iis1.tarot.tarot.Programm#getZeilen <em>Zeilen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Zeilen</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Programm#getZeilen()
   * @see #getProgramm()
   * @generated
   */
  EReference getProgramm_Zeilen();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Zeile <em>Zeile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Zeile</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Zeile
   * @generated
   */
  EClass getZeile();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.Zeile#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Zeile#getName()
   * @see #getZeile()
   * @generated
   */
  EAttribute getZeile_Name();

  /**
   * Returns the meta object for the containment reference '{@link de.fhdw.iis1.tarot.tarot.Zeile#getAnweisung <em>Anweisung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Anweisung</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Zeile#getAnweisung()
   * @see #getZeile()
   * @generated
   */
  EReference getZeile_Anweisung();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Anweisung <em>Anweisung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Anweisung</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Anweisung
   * @generated
   */
  EClass getAnweisung();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Zuordnung <em>Zuordnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Zuordnung</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Zuordnung
   * @generated
   */
  EClass getZuordnung();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.Zuordnung#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Zuordnung#getVar()
   * @see #getZuordnung()
   * @generated
   */
  EAttribute getZuordnung_Var();

  /**
   * Returns the meta object for the containment reference '{@link de.fhdw.iis1.tarot.tarot.Zuordnung#getAusdruck <em>Ausdruck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ausdruck</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Zuordnung#getAusdruck()
   * @see #getZuordnung()
   * @generated
   */
  EReference getZuordnung_Ausdruck();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Ausdruck <em>Ausdruck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ausdruck</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Ausdruck
   * @generated
   */
  EClass getAusdruck();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.StrichOperation <em>Strich Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Strich Operation</em>'.
   * @see de.fhdw.iis1.tarot.tarot.StrichOperation
   * @generated
   */
  EClass getStrichOperation();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.StrichOperation#getLinks <em>Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Links</em>'.
   * @see de.fhdw.iis1.tarot.tarot.StrichOperation#getLinks()
   * @see #getStrichOperation()
   * @generated
   */
  EAttribute getStrichOperation_Links();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.StrichOperation#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see de.fhdw.iis1.tarot.tarot.StrichOperation#getOp()
   * @see #getStrichOperation()
   * @generated
   */
  EAttribute getStrichOperation_Op();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.StrichOperation#getRechts <em>Rechts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rechts</em>'.
   * @see de.fhdw.iis1.tarot.tarot.StrichOperation#getRechts()
   * @see #getStrichOperation()
   * @generated
   */
  EAttribute getStrichOperation_Rechts();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Ganzzahl <em>Ganzzahl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ganzzahl</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Ganzzahl
   * @generated
   */
  EClass getGanzzahl();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.Ganzzahl#getWert <em>Wert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Wert</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Ganzzahl#getWert()
   * @see #getGanzzahl()
   * @generated
   */
  EAttribute getGanzzahl_Wert();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Eingabe <em>Eingabe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Eingabe</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Eingabe
   * @generated
   */
  EClass getEingabe();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.Eingabe#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Eingabe#getVar()
   * @see #getEingabe()
   * @generated
   */
  EAttribute getEingabe_Var();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Ausgabe <em>Ausgabe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ausgabe</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Ausgabe
   * @generated
   */
  EClass getAusgabe();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.Ausgabe#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Ausgabe#getVar()
   * @see #getAusgabe()
   * @generated
   */
  EAttribute getAusgabe_Var();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.GeheZu <em>Gehe Zu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gehe Zu</em>'.
   * @see de.fhdw.iis1.tarot.tarot.GeheZu
   * @generated
   */
  EClass getGeheZu();

  /**
   * Returns the meta object for the reference '{@link de.fhdw.iis1.tarot.tarot.GeheZu#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see de.fhdw.iis1.tarot.tarot.GeheZu#getTarget()
   * @see #getGeheZu()
   * @generated
   */
  EReference getGeheZu_Target();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu <em>Konditionaler Gehe Zu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Konditionaler Gehe Zu</em>'.
   * @see de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu
   * @generated
   */
  EClass getKonditionalerGeheZu();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu#getLinks <em>Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Links</em>'.
   * @see de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu#getLinks()
   * @see #getKonditionalerGeheZu()
   * @generated
   */
  EAttribute getKonditionalerGeheZu_Links();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu#getOp()
   * @see #getKonditionalerGeheZu()
   * @generated
   */
  EAttribute getKonditionalerGeheZu_Op();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu#getRechts <em>Rechts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rechts</em>'.
   * @see de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu#getRechts()
   * @see #getKonditionalerGeheZu()
   * @generated
   */
  EAttribute getKonditionalerGeheZu_Rechts();

  /**
   * Returns the meta object for the reference '{@link de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu#getZiel <em>Ziel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ziel</em>'.
   * @see de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu#getZiel()
   * @see #getKonditionalerGeheZu()
   * @generated
   */
  EReference getKonditionalerGeheZu_Ziel();

  /**
   * Returns the meta object for class '{@link de.fhdw.iis1.tarot.tarot.Halt <em>Halt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Halt</em>'.
   * @see de.fhdw.iis1.tarot.tarot.Halt
   * @generated
   */
  EClass getHalt();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TarotFactory getTarotFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.ProgrammImpl <em>Programm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.ProgrammImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getProgramm()
     * @generated
     */
    EClass PROGRAMM = eINSTANCE.getProgramm();

    /**
     * The meta object literal for the '<em><b>Zeilen</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMM__ZEILEN = eINSTANCE.getProgramm_Zeilen();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.ZeileImpl <em>Zeile</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.ZeileImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getZeile()
     * @generated
     */
    EClass ZEILE = eINSTANCE.getZeile();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZEILE__NAME = eINSTANCE.getZeile_Name();

    /**
     * The meta object literal for the '<em><b>Anweisung</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZEILE__ANWEISUNG = eINSTANCE.getZeile_Anweisung();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.AnweisungImpl <em>Anweisung</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.AnweisungImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getAnweisung()
     * @generated
     */
    EClass ANWEISUNG = eINSTANCE.getAnweisung();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.ZuordnungImpl <em>Zuordnung</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.ZuordnungImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getZuordnung()
     * @generated
     */
    EClass ZUORDNUNG = eINSTANCE.getZuordnung();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZUORDNUNG__VAR = eINSTANCE.getZuordnung_Var();

    /**
     * The meta object literal for the '<em><b>Ausdruck</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZUORDNUNG__AUSDRUCK = eINSTANCE.getZuordnung_Ausdruck();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.AusdruckImpl <em>Ausdruck</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.AusdruckImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getAusdruck()
     * @generated
     */
    EClass AUSDRUCK = eINSTANCE.getAusdruck();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.StrichOperationImpl <em>Strich Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.StrichOperationImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getStrichOperation()
     * @generated
     */
    EClass STRICH_OPERATION = eINSTANCE.getStrichOperation();

    /**
     * The meta object literal for the '<em><b>Links</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRICH_OPERATION__LINKS = eINSTANCE.getStrichOperation_Links();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRICH_OPERATION__OP = eINSTANCE.getStrichOperation_Op();

    /**
     * The meta object literal for the '<em><b>Rechts</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRICH_OPERATION__RECHTS = eINSTANCE.getStrichOperation_Rechts();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.GanzzahlImpl <em>Ganzzahl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.GanzzahlImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getGanzzahl()
     * @generated
     */
    EClass GANZZAHL = eINSTANCE.getGanzzahl();

    /**
     * The meta object literal for the '<em><b>Wert</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GANZZAHL__WERT = eINSTANCE.getGanzzahl_Wert();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.EingabeImpl <em>Eingabe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.EingabeImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getEingabe()
     * @generated
     */
    EClass EINGABE = eINSTANCE.getEingabe();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EINGABE__VAR = eINSTANCE.getEingabe_Var();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.AusgabeImpl <em>Ausgabe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.AusgabeImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getAusgabe()
     * @generated
     */
    EClass AUSGABE = eINSTANCE.getAusgabe();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUSGABE__VAR = eINSTANCE.getAusgabe_Var();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.GeheZuImpl <em>Gehe Zu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.GeheZuImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getGeheZu()
     * @generated
     */
    EClass GEHE_ZU = eINSTANCE.getGeheZu();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GEHE_ZU__TARGET = eINSTANCE.getGeheZu_Target();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.KonditionalerGeheZuImpl <em>Konditionaler Gehe Zu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.KonditionalerGeheZuImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getKonditionalerGeheZu()
     * @generated
     */
    EClass KONDITIONALER_GEHE_ZU = eINSTANCE.getKonditionalerGeheZu();

    /**
     * The meta object literal for the '<em><b>Links</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KONDITIONALER_GEHE_ZU__LINKS = eINSTANCE.getKonditionalerGeheZu_Links();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KONDITIONALER_GEHE_ZU__OP = eINSTANCE.getKonditionalerGeheZu_Op();

    /**
     * The meta object literal for the '<em><b>Rechts</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KONDITIONALER_GEHE_ZU__RECHTS = eINSTANCE.getKonditionalerGeheZu_Rechts();

    /**
     * The meta object literal for the '<em><b>Ziel</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KONDITIONALER_GEHE_ZU__ZIEL = eINSTANCE.getKonditionalerGeheZu_Ziel();

    /**
     * The meta object literal for the '{@link de.fhdw.iis1.tarot.tarot.impl.HaltImpl <em>Halt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.iis1.tarot.tarot.impl.HaltImpl
     * @see de.fhdw.iis1.tarot.tarot.impl.TarotPackageImpl#getHalt()
     * @generated
     */
    EClass HALT = eINSTANCE.getHalt();

  }

} //TarotPackage
