/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Zeile</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.Zeile#getName <em>Name</em>}</li>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.Zeile#getAnweisung <em>Anweisung</em>}</li>
 * </ul>
 *
 * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getZeile()
 * @model
 * @generated
 */
public interface Zeile extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getZeile_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.Zeile#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Anweisung</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Anweisung</em>' containment reference.
   * @see #setAnweisung(Anweisung)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getZeile_Anweisung()
   * @model containment="true"
   * @generated
   */
  Anweisung getAnweisung();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.Zeile#getAnweisung <em>Anweisung</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Anweisung</em>' containment reference.
   * @see #getAnweisung()
   * @generated
   */
  void setAnweisung(Anweisung value);

} // Zeile
