/**
 * generated by Xtext 2.41.0
 */
package de.fhdw.iis1.tarot.tarot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Zuordnung</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.Zuordnung#getVar <em>Var</em>}</li>
 *   <li>{@link de.fhdw.iis1.tarot.tarot.Zuordnung#getAusdruck <em>Ausdruck</em>}</li>
 * </ul>
 *
 * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getZuordnung()
 * @model
 * @generated
 */
public interface Zuordnung extends Anweisung
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getZuordnung_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.Zuordnung#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

  /**
   * Returns the value of the '<em><b>Ausdruck</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ausdruck</em>' containment reference.
   * @see #setAusdruck(Ausdruck)
   * @see de.fhdw.iis1.tarot.tarot.TarotPackage#getZuordnung_Ausdruck()
   * @model containment="true"
   * @generated
   */
  Ausdruck getAusdruck();

  /**
   * Sets the value of the '{@link de.fhdw.iis1.tarot.tarot.Zuordnung#getAusdruck <em>Ausdruck</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ausdruck</em>' containment reference.
   * @see #getAusdruck()
   * @generated
   */
  void setAusdruck(Ausdruck value);

} // Zuordnung
