/*
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class TarotGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProgrammElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Programm");
		private final Assignment cZeilenAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cZeilenZeileParserRuleCall_0 = (RuleCall)cZeilenAssignment.eContents().get(0);
		
		//Programm:
		//    zeilen+=Zeile+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//zeilen+=Zeile+
		public Assignment getZeilenAssignment() { return cZeilenAssignment; }
		
		//Zeile
		public RuleCall getZeilenZeileParserRuleCall_0() { return cZeilenZeileParserRuleCall_0; }
	}
	public class ZeileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Zeile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cAnweisungAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAnweisungAnweisungParserRuleCall_2_0 = (RuleCall)cAnweisungAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Zeile:
		//    name=ID ':' anweisung=Anweisung ';'?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ':' anweisung=Anweisung ';'?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//anweisung=Anweisung
		public Assignment getAnweisungAssignment_2() { return cAnweisungAssignment_2; }
		
		//Anweisung
		public RuleCall getAnweisungAnweisungParserRuleCall_2_0() { return cAnweisungAnweisungParserRuleCall_2_0; }
		
		//';'?
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class AnweisungElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Anweisung");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cZuordnungParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEingabeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAusgabeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cGeheZuParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cKonditionalerGeheZuParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cHaltParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Anweisung:
		//      Zuordnung
		//    | Eingabe
		//    | Ausgabe
		//    | GeheZu
		//    | KonditionalerGeheZu
		//    | Halt
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  Zuordnung
		//| Eingabe
		//| Ausgabe
		//| GeheZu
		//| KonditionalerGeheZu
		//| Halt
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Zuordnung
		public RuleCall getZuordnungParserRuleCall_0() { return cZuordnungParserRuleCall_0; }
		
		//Eingabe
		public RuleCall getEingabeParserRuleCall_1() { return cEingabeParserRuleCall_1; }
		
		//Ausgabe
		public RuleCall getAusgabeParserRuleCall_2() { return cAusgabeParserRuleCall_2; }
		
		//GeheZu
		public RuleCall getGeheZuParserRuleCall_3() { return cGeheZuParserRuleCall_3; }
		
		//KonditionalerGeheZu
		public RuleCall getKonditionalerGeheZuParserRuleCall_4() { return cKonditionalerGeheZuParserRuleCall_4; }
		
		//Halt
		public RuleCall getHaltParserRuleCall_5() { return cHaltParserRuleCall_5; }
	}
	public class ZuordnungElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Zuordnung");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVarAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cVarIDTerminalRuleCall_0_0 = (RuleCall)cVarAssignment_0.eContents().get(0);
		private final Keyword cColonEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cAusdruckAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAusdruckAusdruckParserRuleCall_2_0 = (RuleCall)cAusdruckAssignment_2.eContents().get(0);
		
		//Zuordnung:
		//    var=ID ':=' ausdruck=Ausdruck
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//var=ID ':=' ausdruck=Ausdruck
		public Group getGroup() { return cGroup; }
		
		//var=ID
		public Assignment getVarAssignment_0() { return cVarAssignment_0; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_0_0() { return cVarIDTerminalRuleCall_0_0; }
		
		//':='
		public Keyword getColonEqualsSignKeyword_1() { return cColonEqualsSignKeyword_1; }
		
		//ausdruck=Ausdruck
		public Assignment getAusdruckAssignment_2() { return cAusdruckAssignment_2; }
		
		//Ausdruck
		public RuleCall getAusdruckAusdruckParserRuleCall_2_0() { return cAusdruckAusdruckParserRuleCall_2_0; }
	}
	public class AusdruckElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Ausdruck");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStrichOperationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cGanzzahlParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Ausdruck:
		//    StrichOperation | Ganzzahl
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//StrichOperation | Ganzzahl
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StrichOperation
		public RuleCall getStrichOperationParserRuleCall_0() { return cStrichOperationParserRuleCall_0; }
		
		//Ganzzahl
		public RuleCall getGanzzahlParserRuleCall_1() { return cGanzzahlParserRuleCall_1; }
	}
	public class StrichOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.StrichOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStrichOperationAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cLinksAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLinksIDTerminalRuleCall_1_0 = (RuleCall)cLinksAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cOpAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final Alternatives cOpAlternatives_2_0_0 = (Alternatives)cOpAssignment_2_0.eContents().get(0);
		private final Keyword cOpPlusSignKeyword_2_0_0_0 = (Keyword)cOpAlternatives_2_0_0.eContents().get(0);
		private final Keyword cOpHyphenMinusKeyword_2_0_0_1 = (Keyword)cOpAlternatives_2_0_0.eContents().get(1);
		private final Assignment cRechtsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cRechtsIDTerminalRuleCall_2_1_0 = (RuleCall)cRechtsAssignment_2_1.eContents().get(0);
		
		//StrichOperation:
		//    {StrichOperation}
		//    links=ID (op=('+'|'-') rechts=ID)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{StrichOperation}
		//links=ID (op=('+'|'-') rechts=ID)?
		public Group getGroup() { return cGroup; }
		
		//{StrichOperation}
		public Action getStrichOperationAction_0() { return cStrichOperationAction_0; }
		
		//links=ID
		public Assignment getLinksAssignment_1() { return cLinksAssignment_1; }
		
		//ID
		public RuleCall getLinksIDTerminalRuleCall_1_0() { return cLinksIDTerminalRuleCall_1_0; }
		
		//(op=('+'|'-') rechts=ID)?
		public Group getGroup_2() { return cGroup_2; }
		
		//op=('+'|'-')
		public Assignment getOpAssignment_2_0() { return cOpAssignment_2_0; }
		
		//('+'|'-')
		public Alternatives getOpAlternatives_2_0_0() { return cOpAlternatives_2_0_0; }
		
		//'+'
		public Keyword getOpPlusSignKeyword_2_0_0_0() { return cOpPlusSignKeyword_2_0_0_0; }
		
		//'-'
		public Keyword getOpHyphenMinusKeyword_2_0_0_1() { return cOpHyphenMinusKeyword_2_0_0_1; }
		
		//rechts=ID
		public Assignment getRechtsAssignment_2_1() { return cRechtsAssignment_2_1; }
		
		//ID
		public RuleCall getRechtsIDTerminalRuleCall_2_1_0() { return cRechtsIDTerminalRuleCall_2_1_0; }
	}
	public class GanzzahlElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Ganzzahl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGanzzahlAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cWertAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cWertINTTerminalRuleCall_1_0 = (RuleCall)cWertAssignment_1.eContents().get(0);
		
		//Ganzzahl:
		//    {Ganzzahl}
		//    wert=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Ganzzahl}
		//wert=INT
		public Group getGroup() { return cGroup; }
		
		//{Ganzzahl}
		public Action getGanzzahlAction_0() { return cGanzzahlAction_0; }
		
		//wert=INT
		public Assignment getWertAssignment_1() { return cWertAssignment_1; }
		
		//INT
		public RuleCall getWertINTTerminalRuleCall_1_0() { return cWertINTTerminalRuleCall_1_0; }
	}
	public class EingabeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Eingabe");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEINGABEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVarAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVarIDTerminalRuleCall_1_0 = (RuleCall)cVarAssignment_1.eContents().get(0);
		
		//Eingabe:
		//    'EINGABE' var=ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'EINGABE' var=ID
		public Group getGroup() { return cGroup; }
		
		//'EINGABE'
		public Keyword getEINGABEKeyword_0() { return cEINGABEKeyword_0; }
		
		//var=ID
		public Assignment getVarAssignment_1() { return cVarAssignment_1; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_1_0() { return cVarIDTerminalRuleCall_1_0; }
	}
	public class AusgabeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Ausgabe");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSCHREIBEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVarAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVarIDTerminalRuleCall_1_0 = (RuleCall)cVarAssignment_1.eContents().get(0);
		
		//Ausgabe:
		//    'SCHREIBE' var=ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'SCHREIBE' var=ID
		public Group getGroup() { return cGroup; }
		
		//'SCHREIBE'
		public Keyword getSCHREIBEKeyword_0() { return cSCHREIBEKeyword_0; }
		
		//var=ID
		public Assignment getVarAssignment_1() { return cVarAssignment_1; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_1_0() { return cVarIDTerminalRuleCall_1_0; }
	}
	public class GeheZuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.GeheZu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGEHEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cZUKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTargetAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTargetZeileCrossReference_2_0 = (CrossReference)cTargetAssignment_2.eContents().get(0);
		private final RuleCall cTargetZeileIDTerminalRuleCall_2_0_1 = (RuleCall)cTargetZeileCrossReference_2_0.eContents().get(1);
		
		//GeheZu:
		//    'GEHE' 'ZU' target=[Zeile|ID]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'GEHE' 'ZU' target=[Zeile|ID]
		public Group getGroup() { return cGroup; }
		
		//'GEHE'
		public Keyword getGEHEKeyword_0() { return cGEHEKeyword_0; }
		
		//'ZU'
		public Keyword getZUKeyword_1() { return cZUKeyword_1; }
		
		//target=[Zeile|ID]
		public Assignment getTargetAssignment_2() { return cTargetAssignment_2; }
		
		//[Zeile|ID]
		public CrossReference getTargetZeileCrossReference_2_0() { return cTargetZeileCrossReference_2_0; }
		
		//ID
		public RuleCall getTargetZeileIDTerminalRuleCall_2_0_1() { return cTargetZeileIDTerminalRuleCall_2_0_1; }
	}
	public class KonditionalerGeheZuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.KonditionalerGeheZu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWENNKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLinksAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLinksIDTerminalRuleCall_2_0 = (RuleCall)cLinksAssignment_2.eContents().get(0);
		private final Assignment cOpAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Alternatives cOpAlternatives_3_0 = (Alternatives)cOpAssignment_3.eContents().get(0);
		private final Keyword cOpEqualsSignKeyword_3_0_0 = (Keyword)cOpAlternatives_3_0.eContents().get(0);
		private final Keyword cOpLessThanSignKeyword_3_0_1 = (Keyword)cOpAlternatives_3_0.eContents().get(1);
		private final Keyword cOpGreaterThanSignKeyword_3_0_2 = (Keyword)cOpAlternatives_3_0.eContents().get(2);
		private final Assignment cRechtsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRechtsWertParserRuleCall_4_0 = (RuleCall)cRechtsAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cDANNKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cGEHEKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cZUKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cZielAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cZielZeileCrossReference_9_0 = (CrossReference)cZielAssignment_9.eContents().get(0);
		private final RuleCall cZielZeileIDTerminalRuleCall_9_0_1 = (RuleCall)cZielZeileCrossReference_9_0.eContents().get(1);
		
		//KonditionalerGeheZu:
		//    'WENN' '(' links=ID op=('=' | '<' | '>') rechts=Wert ')'
		//    'DANN' 'GEHE' 'ZU' ziel=[Zeile|ID]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'WENN' '(' links=ID op=('=' | '<' | '>') rechts=Wert ')'
		//'DANN' 'GEHE' 'ZU' ziel=[Zeile|ID]
		public Group getGroup() { return cGroup; }
		
		//'WENN'
		public Keyword getWENNKeyword_0() { return cWENNKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//links=ID
		public Assignment getLinksAssignment_2() { return cLinksAssignment_2; }
		
		//ID
		public RuleCall getLinksIDTerminalRuleCall_2_0() { return cLinksIDTerminalRuleCall_2_0; }
		
		//op=('=' | '<' | '>')
		public Assignment getOpAssignment_3() { return cOpAssignment_3; }
		
		//('=' | '<' | '>')
		public Alternatives getOpAlternatives_3_0() { return cOpAlternatives_3_0; }
		
		//'='
		public Keyword getOpEqualsSignKeyword_3_0_0() { return cOpEqualsSignKeyword_3_0_0; }
		
		//'<'
		public Keyword getOpLessThanSignKeyword_3_0_1() { return cOpLessThanSignKeyword_3_0_1; }
		
		//'>'
		public Keyword getOpGreaterThanSignKeyword_3_0_2() { return cOpGreaterThanSignKeyword_3_0_2; }
		
		//rechts=Wert
		public Assignment getRechtsAssignment_4() { return cRechtsAssignment_4; }
		
		//Wert
		public RuleCall getRechtsWertParserRuleCall_4_0() { return cRechtsWertParserRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//'DANN'
		public Keyword getDANNKeyword_6() { return cDANNKeyword_6; }
		
		//'GEHE'
		public Keyword getGEHEKeyword_7() { return cGEHEKeyword_7; }
		
		//'ZU'
		public Keyword getZUKeyword_8() { return cZUKeyword_8; }
		
		//ziel=[Zeile|ID]
		public Assignment getZielAssignment_9() { return cZielAssignment_9; }
		
		//[Zeile|ID]
		public CrossReference getZielZeileCrossReference_9_0() { return cZielZeileCrossReference_9_0; }
		
		//ID
		public RuleCall getZielZeileIDTerminalRuleCall_9_0_1() { return cZielZeileIDTerminalRuleCall_9_0_1; }
	}
	public class WertElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Wert");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Wert:
		//    ID | INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ID | INT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class HaltElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Halt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cHaltAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cHaltKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Halt:
		//    {Halt} 'Halt!'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Halt} 'Halt!'
		public Group getGroup() { return cGroup; }
		
		//{Halt}
		public Action getHaltAction_0() { return cHaltAction_0; }
		
		//'Halt!'
		public Keyword getHaltKeyword_1() { return cHaltKeyword_1; }
	}
	
	
	private final ProgrammElements pProgramm;
	private final ZeileElements pZeile;
	private final AnweisungElements pAnweisung;
	private final ZuordnungElements pZuordnung;
	private final AusdruckElements pAusdruck;
	private final StrichOperationElements pStrichOperation;
	private final GanzzahlElements pGanzzahl;
	private final EingabeElements pEingabe;
	private final AusgabeElements pAusgabe;
	private final GeheZuElements pGeheZu;
	private final KonditionalerGeheZuElements pKonditionalerGeheZu;
	private final WertElements pWert;
	private final HaltElements pHalt;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TarotGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgramm = new ProgrammElements();
		this.pZeile = new ZeileElements();
		this.pAnweisung = new AnweisungElements();
		this.pZuordnung = new ZuordnungElements();
		this.pAusdruck = new AusdruckElements();
		this.pStrichOperation = new StrichOperationElements();
		this.pGanzzahl = new GanzzahlElements();
		this.pEingabe = new EingabeElements();
		this.pAusgabe = new AusgabeElements();
		this.pGeheZu = new GeheZuElements();
		this.pKonditionalerGeheZu = new KonditionalerGeheZuElements();
		this.pWert = new WertElements();
		this.pHalt = new HaltElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.fhdw.iis1.tarot.Tarot".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Programm:
	//    zeilen+=Zeile+
	//;
	public ProgrammElements getProgrammAccess() {
		return pProgramm;
	}
	
	public ParserRule getProgrammRule() {
		return getProgrammAccess().getRule();
	}
	
	//Zeile:
	//    name=ID ':' anweisung=Anweisung ';'?
	//;
	public ZeileElements getZeileAccess() {
		return pZeile;
	}
	
	public ParserRule getZeileRule() {
		return getZeileAccess().getRule();
	}
	
	//Anweisung:
	//      Zuordnung
	//    | Eingabe
	//    | Ausgabe
	//    | GeheZu
	//    | KonditionalerGeheZu
	//    | Halt
	//;
	public AnweisungElements getAnweisungAccess() {
		return pAnweisung;
	}
	
	public ParserRule getAnweisungRule() {
		return getAnweisungAccess().getRule();
	}
	
	//Zuordnung:
	//    var=ID ':=' ausdruck=Ausdruck
	//;
	public ZuordnungElements getZuordnungAccess() {
		return pZuordnung;
	}
	
	public ParserRule getZuordnungRule() {
		return getZuordnungAccess().getRule();
	}
	
	//Ausdruck:
	//    StrichOperation | Ganzzahl
	//;
	public AusdruckElements getAusdruckAccess() {
		return pAusdruck;
	}
	
	public ParserRule getAusdruckRule() {
		return getAusdruckAccess().getRule();
	}
	
	//StrichOperation:
	//    {StrichOperation}
	//    links=ID (op=('+'|'-') rechts=ID)?
	//;
	public StrichOperationElements getStrichOperationAccess() {
		return pStrichOperation;
	}
	
	public ParserRule getStrichOperationRule() {
		return getStrichOperationAccess().getRule();
	}
	
	//Ganzzahl:
	//    {Ganzzahl}
	//    wert=INT
	//;
	public GanzzahlElements getGanzzahlAccess() {
		return pGanzzahl;
	}
	
	public ParserRule getGanzzahlRule() {
		return getGanzzahlAccess().getRule();
	}
	
	//Eingabe:
	//    'EINGABE' var=ID
	//;
	public EingabeElements getEingabeAccess() {
		return pEingabe;
	}
	
	public ParserRule getEingabeRule() {
		return getEingabeAccess().getRule();
	}
	
	//Ausgabe:
	//    'SCHREIBE' var=ID
	//;
	public AusgabeElements getAusgabeAccess() {
		return pAusgabe;
	}
	
	public ParserRule getAusgabeRule() {
		return getAusgabeAccess().getRule();
	}
	
	//GeheZu:
	//    'GEHE' 'ZU' target=[Zeile|ID]
	//;
	public GeheZuElements getGeheZuAccess() {
		return pGeheZu;
	}
	
	public ParserRule getGeheZuRule() {
		return getGeheZuAccess().getRule();
	}
	
	//KonditionalerGeheZu:
	//    'WENN' '(' links=ID op=('=' | '<' | '>') rechts=Wert ')'
	//    'DANN' 'GEHE' 'ZU' ziel=[Zeile|ID]
	//;
	public KonditionalerGeheZuElements getKonditionalerGeheZuAccess() {
		return pKonditionalerGeheZu;
	}
	
	public ParserRule getKonditionalerGeheZuRule() {
		return getKonditionalerGeheZuAccess().getRule();
	}
	
	//Wert:
	//    ID | INT
	//;
	public WertElements getWertAccess() {
		return pWert;
	}
	
	public ParserRule getWertRule() {
		return getWertAccess().getRule();
	}
	
	//Halt:
	//    {Halt} 'Halt!'
	//;
	public HaltElements getHaltAccess() {
		return pHalt;
	}
	
	public ParserRule getHaltRule() {
		return getHaltAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
