/*
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class TarotGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Program");
		private final Assignment cLinesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cLinesLineParserRuleCall_0 = (RuleCall)cLinesAssignment.eContents().get(0);
		
		//Program:
		//    lines+=Line+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//lines+=Line+
		public Assignment getLinesAssignment() { return cLinesAssignment; }
		
		//Line
		public RuleCall getLinesLineParserRuleCall_0() { return cLinesLineParserRuleCall_0; }
	}
	public class LineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Line");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cInstructionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInstructionInstructionParserRuleCall_2_0 = (RuleCall)cInstructionAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Line:
		//    name=ID ':' instruction=Instruction ';'?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ':' instruction=Instruction ';'?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//instruction=Instruction
		public Assignment getInstructionAssignment_2() { return cInstructionAssignment_2; }
		
		//Instruction
		public RuleCall getInstructionInstructionParserRuleCall_2_0() { return cInstructionInstructionParserRuleCall_2_0; }
		
		//';'?
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Instruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAssignmentParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cInputParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cOutputParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cGotoParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cConditionalGotoParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cStopParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Instruction:
		//      Assignment
		//    | Input
		//    | Output
		//    | Goto
		//    | ConditionalGoto
		//    | Stop
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  Assignment
		//| Input
		//| Output
		//| Goto
		//| ConditionalGoto
		//| Stop
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Assignment
		public RuleCall getAssignmentParserRuleCall_0() { return cAssignmentParserRuleCall_0; }
		
		//Input
		public RuleCall getInputParserRuleCall_1() { return cInputParserRuleCall_1; }
		
		//Output
		public RuleCall getOutputParserRuleCall_2() { return cOutputParserRuleCall_2; }
		
		//Goto
		public RuleCall getGotoParserRuleCall_3() { return cGotoParserRuleCall_3; }
		
		//ConditionalGoto
		public RuleCall getConditionalGotoParserRuleCall_4() { return cConditionalGotoParserRuleCall_4; }
		
		//Stop
		public RuleCall getStopParserRuleCall_5() { return cStopParserRuleCall_5; }
	}
	public class AssignmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Assignment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVarAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cVarIDTerminalRuleCall_0_0 = (RuleCall)cVarAssignment_0.eContents().get(0);
		private final Keyword cColonEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cExprAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cExprExpressionParserRuleCall_2_0 = (RuleCall)cExprAssignment_2.eContents().get(0);
		
		//Assignment:
		//    var=ID ':=' expr=Expression
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//var=ID ':=' expr=Expression
		public Group getGroup() { return cGroup; }
		
		//var=ID
		public Assignment getVarAssignment_0() { return cVarAssignment_0; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_0_0() { return cVarIDTerminalRuleCall_0_0; }
		
		//':='
		public Keyword getColonEqualsSignKeyword_1() { return cColonEqualsSignKeyword_1; }
		
		//expr=Expression
		public Assignment getExprAssignment_2() { return cExprAssignment_2; }
		
		//Expression
		public RuleCall getExprExpressionParserRuleCall_2_0() { return cExprExpressionParserRuleCall_2_0; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAddSubExprParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntLiteralParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Expression:
		//    AddSubExpr | IntLiteral
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//AddSubExpr | IntLiteral
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AddSubExpr
		public RuleCall getAddSubExprParserRuleCall_0() { return cAddSubExprParserRuleCall_0; }
		
		//IntLiteral
		public RuleCall getIntLiteralParserRuleCall_1() { return cIntLiteralParserRuleCall_1; }
	}
	public class AddSubExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.AddSubExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAddSubExprAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cLeftAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLeftIDTerminalRuleCall_1_0 = (RuleCall)cLeftAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cOpAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final Alternatives cOpAlternatives_2_0_0 = (Alternatives)cOpAssignment_2_0.eContents().get(0);
		private final Keyword cOpPlusSignKeyword_2_0_0_0 = (Keyword)cOpAlternatives_2_0_0.eContents().get(0);
		private final Keyword cOpHyphenMinusKeyword_2_0_0_1 = (Keyword)cOpAlternatives_2_0_0.eContents().get(1);
		private final Assignment cRightAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cRightIDTerminalRuleCall_2_1_0 = (RuleCall)cRightAssignment_2_1.eContents().get(0);
		
		//AddSubExpr:
		//    {AddSubExpr}
		//    left=ID (op=('+'|'-') right=ID)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{AddSubExpr}
		//left=ID (op=('+'|'-') right=ID)?
		public Group getGroup() { return cGroup; }
		
		//{AddSubExpr}
		public Action getAddSubExprAction_0() { return cAddSubExprAction_0; }
		
		//left=ID
		public Assignment getLeftAssignment_1() { return cLeftAssignment_1; }
		
		//ID
		public RuleCall getLeftIDTerminalRuleCall_1_0() { return cLeftIDTerminalRuleCall_1_0; }
		
		//(op=('+'|'-') right=ID)?
		public Group getGroup_2() { return cGroup_2; }
		
		//op=('+'|'-')
		public Assignment getOpAssignment_2_0() { return cOpAssignment_2_0; }
		
		//('+'|'-')
		public Alternatives getOpAlternatives_2_0_0() { return cOpAlternatives_2_0_0; }
		
		//'+'
		public Keyword getOpPlusSignKeyword_2_0_0_0() { return cOpPlusSignKeyword_2_0_0_0; }
		
		//'-'
		public Keyword getOpHyphenMinusKeyword_2_0_0_1() { return cOpHyphenMinusKeyword_2_0_0_1; }
		
		//right=ID
		public Assignment getRightAssignment_2_1() { return cRightAssignment_2_1; }
		
		//ID
		public RuleCall getRightIDTerminalRuleCall_2_1_0() { return cRightIDTerminalRuleCall_2_1_0; }
	}
	public class IntLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.IntLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntLiteralAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//IntLiteral:
		//    {IntLiteral}
		//    value=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{IntLiteral}
		//value=INT
		public Group getGroup() { return cGroup; }
		
		//{IntLiteral}
		public Action getIntLiteralAction_0() { return cIntLiteralAction_0; }
		
		//value=INT
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_1_0() { return cValueINTTerminalRuleCall_1_0; }
	}
	public class InputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Input");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEINGABEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVarAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVarIDTerminalRuleCall_1_0 = (RuleCall)cVarAssignment_1.eContents().get(0);
		
		//Input:
		//    'EINGABE' var=ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'EINGABE' var=ID
		public Group getGroup() { return cGroup; }
		
		//'EINGABE'
		public Keyword getEINGABEKeyword_0() { return cEINGABEKeyword_0; }
		
		//var=ID
		public Assignment getVarAssignment_1() { return cVarAssignment_1; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_1_0() { return cVarIDTerminalRuleCall_1_0; }
	}
	public class OutputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Output");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSCHREIBEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVarAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVarIDTerminalRuleCall_1_0 = (RuleCall)cVarAssignment_1.eContents().get(0);
		
		//Output:
		//    'SCHREIBE' var=ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'SCHREIBE' var=ID
		public Group getGroup() { return cGroup; }
		
		//'SCHREIBE'
		public Keyword getSCHREIBEKeyword_0() { return cSCHREIBEKeyword_0; }
		
		//var=ID
		public Assignment getVarAssignment_1() { return cVarAssignment_1; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_1_0() { return cVarIDTerminalRuleCall_1_0; }
	}
	public class GotoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Goto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGEHEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cZUKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTargetAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTargetLineCrossReference_2_0 = (CrossReference)cTargetAssignment_2.eContents().get(0);
		private final RuleCall cTargetLineIDTerminalRuleCall_2_0_1 = (RuleCall)cTargetLineCrossReference_2_0.eContents().get(1);
		
		//Goto:
		//    'GEHE' 'ZU' target=[Line|ID]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'GEHE' 'ZU' target=[Line|ID]
		public Group getGroup() { return cGroup; }
		
		//'GEHE'
		public Keyword getGEHEKeyword_0() { return cGEHEKeyword_0; }
		
		//'ZU'
		public Keyword getZUKeyword_1() { return cZUKeyword_1; }
		
		//target=[Line|ID]
		public Assignment getTargetAssignment_2() { return cTargetAssignment_2; }
		
		//[Line|ID]
		public CrossReference getTargetLineCrossReference_2_0() { return cTargetLineCrossReference_2_0; }
		
		//ID
		public RuleCall getTargetLineIDTerminalRuleCall_2_0_1() { return cTargetLineIDTerminalRuleCall_2_0_1; }
	}
	public class ConditionalGotoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.ConditionalGoto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWENNKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLeftAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLeftIDTerminalRuleCall_2_0 = (RuleCall)cLeftAssignment_2.eContents().get(0);
		private final Assignment cOpAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Alternatives cOpAlternatives_3_0 = (Alternatives)cOpAssignment_3.eContents().get(0);
		private final Keyword cOpEqualsSignKeyword_3_0_0 = (Keyword)cOpAlternatives_3_0.eContents().get(0);
		private final Keyword cOpLessThanSignKeyword_3_0_1 = (Keyword)cOpAlternatives_3_0.eContents().get(1);
		private final Keyword cOpGreaterThanSignKeyword_3_0_2 = (Keyword)cOpAlternatives_3_0.eContents().get(2);
		private final Assignment cRightAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRightValueParserRuleCall_4_0 = (RuleCall)cRightAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cDANNKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cGEHEKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cZUKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cTargetAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cTargetLineCrossReference_9_0 = (CrossReference)cTargetAssignment_9.eContents().get(0);
		private final RuleCall cTargetLineIDTerminalRuleCall_9_0_1 = (RuleCall)cTargetLineCrossReference_9_0.eContents().get(1);
		
		//ConditionalGoto:
		//    'WENN' '(' left=ID op=('=' | '<' | '>') right=Value ')'
		//    'DANN' 'GEHE' 'ZU' target=[Line|ID]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'WENN' '(' left=ID op=('=' | '<' | '>') right=Value ')'
		//'DANN' 'GEHE' 'ZU' target=[Line|ID]
		public Group getGroup() { return cGroup; }
		
		//'WENN'
		public Keyword getWENNKeyword_0() { return cWENNKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//left=ID
		public Assignment getLeftAssignment_2() { return cLeftAssignment_2; }
		
		//ID
		public RuleCall getLeftIDTerminalRuleCall_2_0() { return cLeftIDTerminalRuleCall_2_0; }
		
		//op=('=' | '<' | '>')
		public Assignment getOpAssignment_3() { return cOpAssignment_3; }
		
		//('=' | '<' | '>')
		public Alternatives getOpAlternatives_3_0() { return cOpAlternatives_3_0; }
		
		//'='
		public Keyword getOpEqualsSignKeyword_3_0_0() { return cOpEqualsSignKeyword_3_0_0; }
		
		//'<'
		public Keyword getOpLessThanSignKeyword_3_0_1() { return cOpLessThanSignKeyword_3_0_1; }
		
		//'>'
		public Keyword getOpGreaterThanSignKeyword_3_0_2() { return cOpGreaterThanSignKeyword_3_0_2; }
		
		//right=Value
		public Assignment getRightAssignment_4() { return cRightAssignment_4; }
		
		//Value
		public RuleCall getRightValueParserRuleCall_4_0() { return cRightValueParserRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//'DANN'
		public Keyword getDANNKeyword_6() { return cDANNKeyword_6; }
		
		//'GEHE'
		public Keyword getGEHEKeyword_7() { return cGEHEKeyword_7; }
		
		//'ZU'
		public Keyword getZUKeyword_8() { return cZUKeyword_8; }
		
		//target=[Line|ID]
		public Assignment getTargetAssignment_9() { return cTargetAssignment_9; }
		
		//[Line|ID]
		public CrossReference getTargetLineCrossReference_9_0() { return cTargetLineCrossReference_9_0; }
		
		//ID
		public RuleCall getTargetLineIDTerminalRuleCall_9_0_1() { return cTargetLineIDTerminalRuleCall_9_0_1; }
	}
	public class ValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Value");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Value:
		//    ID | INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ID | INT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class StopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fhdw.iis1.tarot.Tarot.Stop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStopAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cHaltKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Stop:
		//    {Stop} 'Halt!'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Stop} 'Halt!'
		public Group getGroup() { return cGroup; }
		
		//{Stop}
		public Action getStopAction_0() { return cStopAction_0; }
		
		//'Halt!'
		public Keyword getHaltKeyword_1() { return cHaltKeyword_1; }
	}
	
	
	private final ProgramElements pProgram;
	private final LineElements pLine;
	private final InstructionElements pInstruction;
	private final AssignmentElements pAssignment;
	private final ExpressionElements pExpression;
	private final AddSubExprElements pAddSubExpr;
	private final IntLiteralElements pIntLiteral;
	private final InputElements pInput;
	private final OutputElements pOutput;
	private final GotoElements pGoto;
	private final ConditionalGotoElements pConditionalGoto;
	private final ValueElements pValue;
	private final StopElements pStop;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TarotGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pLine = new LineElements();
		this.pInstruction = new InstructionElements();
		this.pAssignment = new AssignmentElements();
		this.pExpression = new ExpressionElements();
		this.pAddSubExpr = new AddSubExprElements();
		this.pIntLiteral = new IntLiteralElements();
		this.pInput = new InputElements();
		this.pOutput = new OutputElements();
		this.pGoto = new GotoElements();
		this.pConditionalGoto = new ConditionalGotoElements();
		this.pValue = new ValueElements();
		this.pStop = new StopElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.fhdw.iis1.tarot.Tarot".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program:
	//    lines+=Line+
	//;
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Line:
	//    name=ID ':' instruction=Instruction ';'?
	//;
	public LineElements getLineAccess() {
		return pLine;
	}
	
	public ParserRule getLineRule() {
		return getLineAccess().getRule();
	}
	
	//Instruction:
	//      Assignment
	//    | Input
	//    | Output
	//    | Goto
	//    | ConditionalGoto
	//    | Stop
	//;
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}
	
	//Assignment:
	//    var=ID ':=' expr=Expression
	//;
	public AssignmentElements getAssignmentAccess() {
		return pAssignment;
	}
	
	public ParserRule getAssignmentRule() {
		return getAssignmentAccess().getRule();
	}
	
	//Expression:
	//    AddSubExpr | IntLiteral
	//;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//AddSubExpr:
	//    {AddSubExpr}
	//    left=ID (op=('+'|'-') right=ID)?
	//;
	public AddSubExprElements getAddSubExprAccess() {
		return pAddSubExpr;
	}
	
	public ParserRule getAddSubExprRule() {
		return getAddSubExprAccess().getRule();
	}
	
	//IntLiteral:
	//    {IntLiteral}
	//    value=INT
	//;
	public IntLiteralElements getIntLiteralAccess() {
		return pIntLiteral;
	}
	
	public ParserRule getIntLiteralRule() {
		return getIntLiteralAccess().getRule();
	}
	
	//Input:
	//    'EINGABE' var=ID
	//;
	public InputElements getInputAccess() {
		return pInput;
	}
	
	public ParserRule getInputRule() {
		return getInputAccess().getRule();
	}
	
	//Output:
	//    'SCHREIBE' var=ID
	//;
	public OutputElements getOutputAccess() {
		return pOutput;
	}
	
	public ParserRule getOutputRule() {
		return getOutputAccess().getRule();
	}
	
	//Goto:
	//    'GEHE' 'ZU' target=[Line|ID]
	//;
	public GotoElements getGotoAccess() {
		return pGoto;
	}
	
	public ParserRule getGotoRule() {
		return getGotoAccess().getRule();
	}
	
	//ConditionalGoto:
	//    'WENN' '(' left=ID op=('=' | '<' | '>') right=Value ')'
	//    'DANN' 'GEHE' 'ZU' target=[Line|ID]
	//;
	public ConditionalGotoElements getConditionalGotoAccess() {
		return pConditionalGoto;
	}
	
	public ParserRule getConditionalGotoRule() {
		return getConditionalGotoAccess().getRule();
	}
	
	//Value:
	//    ID | INT
	//;
	public ValueElements getValueAccess() {
		return pValue;
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}
	
	//Stop:
	//    {Stop} 'Halt!'
	//;
	public StopElements getStopAccess() {
		return pStop;
	}
	
	public ParserRule getStopRule() {
		return getStopAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
