/*
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TarotUiModule extends AbstractTarotUiModule {

	public TarotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
