/*
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class TarotScopeProvider extends AbstractTarotScopeProvider {

}
