/**
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.tarot.util;

import de.fhdw.iis1.tarot.tarot.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see de.fhdw.iis1.tarot.tarot.TarotPackage
 * @generated
 */
public class TarotAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static TarotPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TarotAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = TarotPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TarotSwitch<Adapter> modelSwitch =
    new TarotSwitch<Adapter>()
    {
      @Override
      public Adapter caseProgramm(Programm object)
      {
        return createProgrammAdapter();
      }
      @Override
      public Adapter caseZeile(Zeile object)
      {
        return createZeileAdapter();
      }
      @Override
      public Adapter caseAnweisung(Anweisung object)
      {
        return createAnweisungAdapter();
      }
      @Override
      public Adapter caseZuordnung(Zuordnung object)
      {
        return createZuordnungAdapter();
      }
      @Override
      public Adapter caseAusdruck(Ausdruck object)
      {
        return createAusdruckAdapter();
      }
      @Override
      public Adapter caseStrichOperation(StrichOperation object)
      {
        return createStrichOperationAdapter();
      }
      @Override
      public Adapter caseGanzzahl(Ganzzahl object)
      {
        return createGanzzahlAdapter();
      }
      @Override
      public Adapter caseEingabe(Eingabe object)
      {
        return createEingabeAdapter();
      }
      @Override
      public Adapter caseAusgabe(Ausgabe object)
      {
        return createAusgabeAdapter();
      }
      @Override
      public Adapter caseGeheZu(GeheZu object)
      {
        return createGeheZuAdapter();
      }
      @Override
      public Adapter caseKonditionalerGeheZu(KonditionalerGeheZu object)
      {
        return createKonditionalerGeheZuAdapter();
      }
      @Override
      public Adapter caseHalt(Halt object)
      {
        return createHaltAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link de.fhdw.iis1.tarot.tarot.Programm <em>Programm</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.fhdw.iis1.tarot.tarot.Programm
   * @generated
   */
  public Adapter createProgrammAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.fhdw.iis1.tarot.tarot.Zeile <em>Zeile</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.fhdw.iis1.tarot.tarot.Zeile
   * @generated
   */
  public Adapter createZeileAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.fhdw.iis1.tarot.tarot.Anweisung <em>Anweisung</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.fhdw.iis1.tarot.tarot.Anweisung
   * @generated
   */
  public Adapter createAnweisungAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.fhdw.iis1.tarot.tarot.Zuordnung <em>Zuordnung</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.fhdw.iis1.tarot.tarot.Zuordnung
   * @generated
   */
  public Adapter createZuordnungAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.fhdw.iis1.tarot.tarot.Ausdruck <em>Ausdruck</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.fhdw.iis1.tarot.tarot.Ausdruck
   * @generated
   */
  public Adapter createAusdruckAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.fhdw.iis1.tarot.tarot.StrichOperation <em>Strich Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.fhdw.iis1.tarot.tarot.StrichOperation
   * @generated
   */
  public Adapter createStrichOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.fhdw.iis1.tarot.tarot.Ganzzahl <em>Ganzzahl</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.fhdw.iis1.tarot.tarot.Ganzzahl
   * @generated
   */
  public Adapter createGanzzahlAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.fhdw.iis1.tarot.tarot.Eingabe <em>Eingabe</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.fhdw.iis1.tarot.tarot.Eingabe
   * @generated
   */
  public Adapter createEingabeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.fhdw.iis1.tarot.tarot.Ausgabe <em>Ausgabe</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.fhdw.iis1.tarot.tarot.Ausgabe
   * @generated
   */
  public Adapter createAusgabeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.fhdw.iis1.tarot.tarot.GeheZu <em>Gehe Zu</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.fhdw.iis1.tarot.tarot.GeheZu
   * @generated
   */
  public Adapter createGeheZuAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu <em>Konditionaler Gehe Zu</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu
   * @generated
   */
  public Adapter createKonditionalerGeheZuAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.fhdw.iis1.tarot.tarot.Halt <em>Halt</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.fhdw.iis1.tarot.tarot.Halt
   * @generated
   */
  public Adapter createHaltAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //TarotAdapterFactory
