/*
 * generated by Xtext 2.41.0
 */
package de.fhdw.iis1.tarot.parser.antlr;

import com.google.inject.Inject;
import de.fhdw.iis1.tarot.parser.antlr.internal.InternalTarotParser;
import de.fhdw.iis1.tarot.services.TarotGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TarotParser extends AbstractAntlrParser {

	@Inject
	private TarotGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTarotParser createParser(XtextTokenStream stream) {
		return new InternalTarotParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Programm";
	}

	public TarotGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TarotGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
