/*
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TarotAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/fhdw/iis1/tarot/parser/antlr/internal/InternalTarot.tokens");
	}
}
