/*
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTarotValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(de.fhdw.iis1.tarot.tarot.TarotPackage.eINSTANCE);
		return result;
	}
}
