/*
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.fhdw.iis1.tarot.TarotRuntimeModule;
import de.fhdw.iis1.tarot.TarotStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TarotIdeSetup extends TarotStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TarotRuntimeModule(), new TarotIdeModule()));
	}
	
}
