/*
 * generated by Xtext 2.41.0
 */
package de.fhdw.iis1.tarot.ui;

import com.google.inject.Injector;
import de.fhdw.iis1.tarot.ui.internal.TarotActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TarotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TarotActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TarotActivator activator = TarotActivator.getInstance();
		return activator != null ? activator.getInjector(TarotActivator.DE_FHDW_IIS1_TAROT_TAROT) : null;
	}

}
