/*
 * generated by Xtext 2.41.0
 */
package de.fhdw.iis1.tarot.serializer;

import com.google.inject.Inject;
import de.fhdw.iis1.tarot.services.TarotGrammarAccess;
import de.fhdw.iis1.tarot.tarot.Ausgabe;
import de.fhdw.iis1.tarot.tarot.Eingabe;
import de.fhdw.iis1.tarot.tarot.Ganzzahl;
import de.fhdw.iis1.tarot.tarot.GeheZu;
import de.fhdw.iis1.tarot.tarot.Halt;
import de.fhdw.iis1.tarot.tarot.KonditionalerGeheZu;
import de.fhdw.iis1.tarot.tarot.Programm;
import de.fhdw.iis1.tarot.tarot.StrichOperation;
import de.fhdw.iis1.tarot.tarot.TarotPackage;
import de.fhdw.iis1.tarot.tarot.Zeile;
import de.fhdw.iis1.tarot.tarot.Zuordnung;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class TarotSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private TarotGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == TarotPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case TarotPackage.AUSGABE:
				sequence_Ausgabe(context, (Ausgabe) semanticObject); 
				return; 
			case TarotPackage.EINGABE:
				sequence_Eingabe(context, (Eingabe) semanticObject); 
				return; 
			case TarotPackage.GANZZAHL:
				sequence_Ganzzahl(context, (Ganzzahl) semanticObject); 
				return; 
			case TarotPackage.GEHE_ZU:
				sequence_GeheZu(context, (GeheZu) semanticObject); 
				return; 
			case TarotPackage.HALT:
				sequence_Halt(context, (Halt) semanticObject); 
				return; 
			case TarotPackage.KONDITIONALER_GEHE_ZU:
				sequence_KonditionalerGeheZu(context, (KonditionalerGeheZu) semanticObject); 
				return; 
			case TarotPackage.PROGRAMM:
				sequence_Programm(context, (Programm) semanticObject); 
				return; 
			case TarotPackage.STRICH_OPERATION:
				sequence_StrichOperation(context, (StrichOperation) semanticObject); 
				return; 
			case TarotPackage.ZEILE:
				sequence_Zeile(context, (Zeile) semanticObject); 
				return; 
			case TarotPackage.ZUORDNUNG:
				sequence_Zuordnung(context, (Zuordnung) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Anweisung returns Ausgabe
	 *     Ausgabe returns Ausgabe
	 *
	 * Constraint:
	 *     var=ID
	 * </pre>
	 */
	protected void sequence_Ausgabe(ISerializationContext context, Ausgabe semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TarotPackage.Literals.AUSGABE__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TarotPackage.Literals.AUSGABE__VAR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAusgabeAccess().getVarIDTerminalRuleCall_1_0(), semanticObject.getVar());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Anweisung returns Eingabe
	 *     Eingabe returns Eingabe
	 *
	 * Constraint:
	 *     var=ID
	 * </pre>
	 */
	protected void sequence_Eingabe(ISerializationContext context, Eingabe semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TarotPackage.Literals.EINGABE__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TarotPackage.Literals.EINGABE__VAR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEingabeAccess().getVarIDTerminalRuleCall_1_0(), semanticObject.getVar());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Ausdruck returns Ganzzahl
	 *     Ganzzahl returns Ganzzahl
	 *
	 * Constraint:
	 *     wert=INT
	 * </pre>
	 */
	protected void sequence_Ganzzahl(ISerializationContext context, Ganzzahl semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TarotPackage.Literals.GANZZAHL__WERT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TarotPackage.Literals.GANZZAHL__WERT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getGanzzahlAccess().getWertINTTerminalRuleCall_1_0(), semanticObject.getWert());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Anweisung returns GeheZu
	 *     GeheZu returns GeheZu
	 *
	 * Constraint:
	 *     ziel=ID
	 * </pre>
	 */
	protected void sequence_GeheZu(ISerializationContext context, GeheZu semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TarotPackage.Literals.GEHE_ZU__ZIEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TarotPackage.Literals.GEHE_ZU__ZIEL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getGeheZuAccess().getZielIDTerminalRuleCall_2_0(), semanticObject.getZiel());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Anweisung returns Halt
	 *     Halt returns Halt
	 *
	 * Constraint:
	 *     {Halt}
	 * </pre>
	 */
	protected void sequence_Halt(ISerializationContext context, Halt semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Anweisung returns KonditionalerGeheZu
	 *     KonditionalerGeheZu returns KonditionalerGeheZu
	 *
	 * Constraint:
	 *     (
	 *         links=Wert 
	 *         (
	 *             op='=' | 
	 *             op='&lt;' | 
	 *             op='&gt;' | 
	 *             op='&lt;=' | 
	 *             op='&gt;=' | 
	 *             op='!='
	 *         ) 
	 *         rechts=Wert 
	 *         ziel=ID
	 *     )
	 * </pre>
	 */
	protected void sequence_KonditionalerGeheZu(ISerializationContext context, KonditionalerGeheZu semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Programm returns Programm
	 *
	 * Constraint:
	 *     zeilen+=Zeile+
	 * </pre>
	 */
	protected void sequence_Programm(ISerializationContext context, Programm semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Ausdruck returns StrichOperation
	 *     StrichOperation returns StrichOperation
	 *
	 * Constraint:
	 *     (links=ID (op='+' | op='-') rechts=ID)
	 * </pre>
	 */
	protected void sequence_StrichOperation(ISerializationContext context, StrichOperation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Zeile returns Zeile
	 *
	 * Constraint:
	 *     (name=ID anweisung=Anweisung)
	 * </pre>
	 */
	protected void sequence_Zeile(ISerializationContext context, Zeile semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TarotPackage.Literals.ZEILE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TarotPackage.Literals.ZEILE__NAME));
			if (transientValues.isValueTransient(semanticObject, TarotPackage.Literals.ZEILE__ANWEISUNG) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TarotPackage.Literals.ZEILE__ANWEISUNG));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getZeileAccess().getNameIDTerminalRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getZeileAccess().getAnweisungAnweisungParserRuleCall_2_0(), semanticObject.getAnweisung());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Anweisung returns Zuordnung
	 *     Zuordnung returns Zuordnung
	 *
	 * Constraint:
	 *     (var=ID ausdruck=Ausdruck)
	 * </pre>
	 */
	protected void sequence_Zuordnung(ISerializationContext context, Zuordnung semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TarotPackage.Literals.ZUORDNUNG__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TarotPackage.Literals.ZUORDNUNG__VAR));
			if (transientValues.isValueTransient(semanticObject, TarotPackage.Literals.ZUORDNUNG__AUSDRUCK) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TarotPackage.Literals.ZUORDNUNG__AUSDRUCK));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getZuordnungAccess().getVarIDTerminalRuleCall_0_0(), semanticObject.getVar());
		feeder.accept(grammarAccess.getZuordnungAccess().getAusdruckAusdruckParserRuleCall_2_0(), semanticObject.getAusdruck());
		feeder.finish();
	}
	
	
}
