/*
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TarotStandaloneSetup extends TarotStandaloneSetupGenerated {

	public static void doSetup() {
		new TarotStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
