/*
 * generated by Xtext 2.43.0
 */
package de.fhdw.iis1.tarot.ui.tests;

import com.google.inject.Injector;
import de.fhdw.iis1.tarot.ui.internal.TarotActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TarotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TarotActivator.getInstance().getInjector("de.fhdw.iis1.tarot.Tarot");
	}

}
